### PR TITLE
Added Music Generation with LSTM

### PR DESCRIPTION
**Pull request by Soubeer**
In this project, I developed a music generation model using Long Short-Term Memory networks to create new musical compositions. By training the LSTM model on a dataset of MIDI files, it learns the sequences and patterns inherent in the music. This enables the model to generate original music pieces that mimic the style and structure of the training data, showcasing the potential of LSTM networks in creative applications such as automated music composition and music style emulation.

It uses the unsplash dataset , which is very useful and effective in this scenario.

It gives out generated music according to personal preference and likings of the user keeping in mind the qualities that the user demands.

Fixes#551

### CODE REVIEW

**Comment by invigorzz313** [comment]
Please tag the corresponding issue.

**Comment by Soubeer** [comment]
> Please tag the corresponding issue.

added the issue number 
also can you give me a level for this PR? Its needed for the leaderboard

**Comment by invigorzz313** [comment]
@Soubeer while making a PR, you have to create a new branch first. Avoid committing from the master branch of your forked/cloned repo.

**Comment by invigorzz313** [comment]
Looks like no cell is run in the .ipynb file you contributed.
Avoid duplicate code lines.
Level labels can't be attached unless you resolve these issues.

**Comment by Soubeer** [comment]
@invigorzz313 im closing this PR and creating a new one where I am merging the branch that I made. I am sorry I am new to git so it took me a while to understand these branches.

**Pull request closed without merging**
