### PR TITLE
Gesture Control Mouse - Final

### PR DESCRIPTION
**Pull request by Purva-Gharat**
Issue Number - #472 

All required changes have been done.

### CODE REVIEW

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
Please recheck your ipynb file.

**Comment by Purva-Gharat** [comment]
> Please recheck your ipynb file.

yes I have checked.. that last comments are just a warnings after running the project successfully

**Comment by Rutikab12** [comment]
> > Please recheck your ipynb file.
> 
> yes I have checked.. that last comments are just a warnings after running the project successfully

Okay. I will re-run it.

**Review by Rutikab12 — APPROVED** [review]

**Comment by Purva-Gharat** [comment]
Thank you so much!

**Comment by Purva-Gharat** [comment]
Can you please merge this PR into the main branch

**Comment by Rutikab12** [comment]
> Can you please merge this PR into the main branch

Admin will check once again. Wait till then.

**Comment by Purva-Gharat** [comment]
> > Can you please merge this PR into the main branch
> 
> Admin will check once again. Wait till then.

Okay!

**Pull request merged**
