### PR TITLE
Added Road accident analysis project using Power BI

### PR DESCRIPTION
**Pull request by jeet-Abhi123**
I have successfully added the project as a new folder in the repository.

### CODE REVIEW

**Comment by invigorzz313** [comment]
Please tag the corresponding issue.

**Comment by jeet-Abhi123** [comment]
#622 
#623

**Comment by invigorzz313** [comment]
@jeet-Abhi123 You seem to have created this PR for 2 issues of different topics.
It is suggested that a single PR fixes single issue. So, please create separate ones.

**Comment by jeet-Abhi123** [comment]
How can I create different PR? When I clicked the PR of issue #623 it is getting adding to this PR only.

**Comment by invigorzz313** [comment]
@jeet-Abhi123 That is because you mentioned 2 issue numbers above (622 and 623).
Also the files you uploaded in the commit in this PR have both Road accident analysis and Data Cleaning Techniques.
Since this PR is for Road Accident Analysis, retain these files and delete others from this PR.
You can make another PR with Data Cleaning files and tag issue 623 there.

**Comment by invigorzz313** [comment]
For creating another PR, you must first create another branch in your local repo. And commit the relevant files there.
(Separate issue <-> separate PR <-> separate branch)

**Pull request closed without merging**
