### PR TITLE
Web scraping bs4

### LINKED ISSUE #592: Add to Web-Scraping-with-Beautiful-Soup-master and remove invalid notebooks.
There are multiple ipynb files in Web-Scraping-with-Beautiful-Soup-master folder that do not appear to Be Valid JSONs. I would like to remove these files and add programs for extracting data from websites like Wikipedia and Amazon. 
Please assign this issue to me @Niketkumardheeryan .
Additional info for tags: I am participating as contributor through gssoc' 24.

### PR DESCRIPTION
**Pull request by speckofstardust**
resolved #592 by: 
1. Removing multiple .ipynb files with invalid JSON.
2.  Demonstrated web scraping on 
     i) https://realpython.github.io/fake-jobs/ site which is an example site with fake job postings that you can freely scrape to train your skills and 
    ii)amazon product review

The idea of scraping a Wikipedia page as mentioned in the issue was not pursued due to unclear terms and conditions regarding its legality.

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
hi @speckofstardust , good work but try to improve your coding style, you are just using 2 or 3 cells to write your whole code , try to add more cell or comments in your code .

**Comment by speckofstardust** [comment]
hello @Niketkumardheeryan ! Thank you for reviewing and suggesting improvements in my coding style. I've made the suggested changes now.
I also had to use a different product to scrap reviews from in the amazon product review due to accidentally triggering CAPTCHA in the old one. 
These are the changes I've made this time. Please let me know if there is anything else.

**Comment by Niketkumardheeryan** [comment]
@speckofstardust please wrap your output as it's creating confusion, please add proper comments, Improve your readme.md file as well

**Comment by speckofstardust** [comment]
hi @Niketkumardheeryan 
I've updated the readme.md file add added appropriate comments now. 
Not sure what you mean by wrapping output though? Could you please elaborate on that? 
If it's the length of some of the outputs that's causing confusion, i can try putting them in a .txt or .md file for reference. Is that what you meant?

**Pull request merged**
