### PR TITLE
here is my update pull request with read me please look into it

### PR DESCRIPTION
**Pull request by PRIYANSHU2026**
thank you for guiding its mean a lot

### CODE REVIEW

**Comment by invigorzz313** [comment]
Please tag the corresponding issue.

**Comment by PRIYANSHU2026** [comment]
Done mam

**Comment by invigorzz313** [comment]
For a PR to be accepted, first you must raise an issue about it and get it accepted. And that issue number must be tagged here, i.e., in the PR. (Eg., Fixes #615)

**Comment by invigorzz313** [comment]
LGTM but can you please deploy the ML model?

**Comment by PRIYANSHU2026** [comment]
That model is in that ipynb  when will put our stats they will predict

**Comment by PRIYANSHU2026** [comment]
Mam or sir please accept my pull request

**Comment by Niketkumardheeryan** [comment]
hey @PRIYANSHU2026  please make PR again IN Capsule 1.1 Branch as we are enable to track the exact issue,

**Comment by Niketkumardheeryan** [comment]
Branch Name - Capsule 1.1

**Pull request closed without merging**
