### PR TITLE
Word cloud

### PR DESCRIPTION
**Pull request by mohanadtalat91**
### Adding Word Cloud Project.

Issue number :  #361 

**Description** 

Word Cloud or Tag Clouds is a visualization technique for texts that are natively used for visualizing the tags or keywords from the websites. These keywords typically are single words that depict the context of the webpage the word cloud is being made from. These words are clustered together to form a Word Cloud.

Each word in this cloud has a variable font size and color tone. Thus, this representation helps to determine words of prominence. A bigger font size of a word portrays its prominence more relative to other words in the cluster. Word Cloud can be built in varying shapes and sizes based on the creators’ vision. The number of words plays an important role while creating a Word Cloud. More number of words does not always mean a better Word Cloud as it becomes cluttery and difficult to read. A Word Cloud must always be semantically meaningful and must represent what it is meant for.

### CODE REVIEW

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
@mohanadtalat91  Here also add a proper readme file.

**Comment by mohanadtalat91** [comment]
> @mohanadtalat91 Here also add a proper readme file.

Issue number : #361

**Comment by mohanadtalat91** [comment]
> @mohanadtalat91 Here also add a proper readme file.

I've Updated README file & Assign an issue number

**Comment by Niketkumardheeryan** [comment]
> > @mohanadtalat91 Here also add a proper readme file.
> 
> I've Updated the README file & Assign an issue number

add a proper readme.md file

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
Hey @mohanadtalat91 , make a readme file about your project. You have lot of irrelevant details in your readme.

**Comment by mohanadtalat91** [comment]
> Hey @mohanadtalat91 , make a readme file about your project. You have lot of irrelevant details in your readme.

**Comment by mohanadtalat91** [comment]
> Hey @mohanadtalat91 , make a readme file about your project. You have lot of irrelevant details in your readme.

I've craeted README file for the project

**Review by Rutikab12 — APPROVED** [review]

**Comment by mohanadtalat91** [comment]
@Rutikab12
When will be merged ?

**Comment by mohanadtalat91** [comment]
> Why have you added the README file to the Repository? Please remove it from your commit. ANd keep Readme file of your project only.

Does it fit now ??
@Rutikab12

**Comment by mohanadtalat91** [comment]
@Niketkumardheeryan
@Rutikab12

Is it okay or I missed something ?

**Comment by Niketkumardheeryan** [comment]
> @Niketkumardheeryan @Rutikab12
> 
> Is it okay or I missed something ?

@pratishthaa @subhadeeppaul check it

**Review by pratishthaa — COMMENTED** [review]
Looks fine

**Comment by subhadeeppaul** [comment]
@Niketkumardheeryan yeah looks fine

**Comment by mohanadtalat91** [comment]
Hi @Niketkumardheeryan,
Why did you close it although both reviewers said that fine ??!!

**Pull request closed without merging**
