### PR TITLE
Added Student marks and performance predictor

### LINKED ISSUE #960: Student Marks and performance prediction using machine learning
This project aims to predict the estimated marks and grade of students based on various inputted factors using  given dataset from Kaggle :

https://www.kaggle.com/datasets/nikhil7280/student-performance-multiple-linear-regression

This dataset includes columns like :
Hours Studied: The total number of hours spent studying by each student.
Previous Scores: The scores obtained by students in previous tests.
Extracurricular Activities: Whether the student participates in extracurricular activities (Yes or No).
Sleep Hours: The average number of hours of sleep the student had per day.
Sample Question Papers Practiced: The number of sample question papers the student practiced.

i will apply different machine learning models and find out which is most accurate ,do EDA , will do a compete data analysis , feature engineering etc. i will take input from user and do predict on Streamlit based Gui application.

### PR DESCRIPTION
**Pull request by RajKhanke**
resolves #960 

https://github.com/user-attachments/assets/48f5643a-ba8b-4b4c-8523-6e34dcb2dd30

### CODE REVIEW

**Comment by RajKhanke** [comment]
@Niketkumardheeryan @invigorzz313 please merge this pr along with level and label. it will resolve issue no.960

**Comment by invigorzz313** [comment]
@RajKhanke You'll have to run all the cells in the .ipynb file. EDA and feature engg sections..

**Comment by RajKhanke** [comment]
@invigorzz313 @Niketkumardheeryan i have updated the required changes, please try to consider to merge this PR along with level and label

**Comment by invigorzz313** [comment]
@RajKhanke seems no change. Those sections are not run. figure.show() commands

**Comment by Niketkumardheeryan** [comment]
And this kind of model is already there ,so please create new issue now

**Pull request closed without merging**
