### PR TITLE
image captioning added 

### LINKED ISSUE #658: Image Captioning
I noticed a lack of **image captioning** work in the repository right now. Implementing image captioning using machine learning is a challenging task, but would greatly benefit learners to understanding the concept of  concatenation of two inputs , and more about image processing with nlp.
I'm interested in contributing to this aspect of the project.
 Can you  assign this issue to me?

### PR DESCRIPTION
**Pull request by HazSyl1**
Added notebooks, data, and relevant information on image captioning using deep learning. The process is briefly explained in the README file, along with the model diagram. Resolves #658 .

### CODE REVIEW

**Comment by invigorzz313** [comment]
LGTM but can you remove the empty "Image Captioning/Model Files/Readme.md.bak" file if it has no use?

**Comment by Niketkumardheeryan** [comment]
Hi @HazSyl1 , good work , but please add images of of your results  and accuracy with different pretrained model or CNN, And i found your code is not much readable , No Image preprocessing (visualize) , try to add accuracy chart as well

**Comment by Niketkumardheeryan** [comment]
@HazSyl1 any update ,otherwise will close the PR.

**Comment by HazSyl1** [comment]
Yes the task is almost done . I'll be pushing the complete repo in a while.

**Comment by HazSyl1** [comment]
Hi, in the latest commit. I've elaborated the code clearly and concisely. And I've performed model testing and evaluation mentioning the scores as well. Apart from this, I've added visualization of the architecture used and how its filters affect the image to get a feature map.

**Pull request merged**
