### PR TITLE
Real Time Facial Landmark Detector

### PR DESCRIPTION
**Pull request by yashh18**

### CODE REVIEW

**Review by pratishthaa — CHANGES_REQUESTED** [review]
1. Submit code in ipynb format only
2. Deploy your project as a website or app
3. Then, Add a sample video of how the model works, and add it to readme

**Comment by pratishthaa** [comment]
@hritikksingh @Rutikab12 @Niketkumardheeryan Please add if you have any other change requests.

**Comment by hritikksingh** [comment]
I think it's fine, if you are using cv2 for taking video input and showing live face landmarks in the frame itself. Is it? @Niketkumardheeryan

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
do the changes suggested by @pratishthaa

**Comment by yashh18** [comment]
@pratishthaa actually i am not well versed with flutter, so I won't be able to deploy it :(

**Comment by Niketkumardheeryan** [comment]
> @pratishthaa actually i am not well versed with flutter, so I won't be able to deploy it :(

it is okay if can't deploy, but add .ipynb file of your code with a proper readme.md file ...

**Pull request closed without merging**
