### PR TITLE
add image-scraping tool

### PR DESCRIPTION
**Pull request by ASHWIN492**
- This is a Flask application for scraping images from Google search results and storing them in a MongoDB database.
 #543 issue is solved

### CODE REVIEW

**Comment by ASHWIN492** [comment]
@Niketkumardheeryan can you review it I have resolved the issue

**Comment by ASHWIN492** [comment]
Please review and merge this PR @Niketkumardheeryan  @invigorzz313

**Comment by Niketkumardheeryan** [comment]
@ASHWIN492 add result imgs in the readme.md file and try to add .ipynb instead of .py with more comments for Better readability.

**Comment by Niketkumardheeryan** [comment]
@ASHWIN492 any update????????

**Comment by ASHWIN492** [comment]
@Niketkumardheeryan sorry for the delay i will update in 1-2 days.

**Comment by Niketkumardheeryan** [comment]
Create a new PR now

**Pull request closed without merging**
