### PR TITLE
Recognition of gestures and action

### PR DESCRIPTION
**Pull request by Pranshu-jais**
created Recognition_of_gestures_and_action using  pre-trained neural network pose_deploy_linevec_faster_4_stages.prototxt and pose_iter_160000.caffemodel  and uploaded the result video as gesture1_result

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
add readme.md file.

**Comment by Pranshu-jais** [comment]
I have added readme.md file.

**Comment by Niketkumardheeryan** [comment]
Hi @Pranshu-jais , add how can a we use this project and add proper screenshots in Readme.md file, you can also explain why did you used these library .

**Comment by Pranshu-jais** [comment]
i have updated the readme.md file

**Comment by Pranshu-jais** [comment]
Thank you sir for guiding me and pointing out correction i needed to do .

**Pull request merged**
