### PR TITLE
Implementation of frontend

### PR DESCRIPTION
**Pull request by AKing-283**
**Frontend Integration**
Integrated **Gradio** which is a good UI for ML projects and with this user can enter the news and can get that whether this news is real or fake. It is a basic UI you can use streamlit as well.

### CODE REVIEW

**Comment by invigorzz313** [comment]
Hey @AKing-283, why do I see the main Readme.md file of this project repo edited in your commit? The projects list has been deleted in there?

**Comment by AKing-283** [comment]
> Hey @AKing-283, why do I see the main Readme.md file of this project repo edited in your commit? The projects list has been deleted in there?

I have just made a pull request and made my commits in there

**Comment by AKing-283** [comment]
I have to make pr in the forked one right

**Comment by AKing-283** [comment]
I will make a pr and let you know @invigorzz313 , pls tell me whether I made a pr correctly or not

**Comment by AKing-283** [comment]
Screenshot 2024-05-24 at 11 21 24 PM
I was facing this error in gradio @invigorzz313 pls help me out

**Pull request closed without merging**
