### PR TITLE
K-Means Clustering on Mall Customers Data: Beginner-friendly Project

### PR DESCRIPTION
**Pull request by Hannan2004**
This pull request adds a K-Means clustering project on Mall Customers data to the repository. The aim of this project is to provide a beginner-friendly introduction to K-Means clustering and its application in customer segmentation. The project includes steps to preprocess the data, apply the K-Means algorithm, and visualize the resulting clusters. By following this project, beginners can gain hands-on experience with K-Means clustering and understand its practical utility in real-world scenarios, particularly in marketing. Adding this project to the repository offers a valuable learning opportunity for individuals interested in machine learning and data analysis. It serves as a stepping stone for beginners to explore more advanced clustering techniques and apply them to diverse datasets in the future.

### CODE REVIEW

**Comment by invigorzz313** [comment]
An issue must be created first and only then you can work on a PR after it is assigned.
If you have already created one and has it assigned to you, please tag it in the PR.

Also in this PR, there are commits of other files unrelated to the objective.

**Comment by sudiptasarkar011** [comment]
I would like to work on this project, can you please assign this to me?

**Comment by Hannan2004** [comment]
> An issue must be created first and only then you can work on a PR after it is assigned.
> If you have already created one and has it assigned to you, please tag it in the PR.
> 
> Also in this PR, there are commits of other files unrelated to the objective.

Is it mention in the contributing guide on how to tag a PR?if yes please tell me so that I can get it done.

**Comment by invigorzz313** [comment]
> > An issue must be created first and only then you can work on a PR after it is assigned.
> > If you have already created one and has it assigned to you, please tag it in the PR.
> > Also in this PR, there are commits of other files unrelated to the objective.
> 
> Is it mention in the contributing guide on how to tag a PR?if yes please tell me so that I can get it done.

If you have created an issue for this, tagging here is to comment in your description: #abc where abc is your issue number.

**Comment by Hannan2004** [comment]
### Pull Request for ML-CaPsule 💡

**Issue Title:** Added project using K-means clustering algorithm on mall customers data to segment them

**Project Name:** Mall Customer Segmentation

**Category:** Machine Learning

**Name:** Abdul Hannan Chougle

**GitHub ID:** https://github.com/Hannan2004

**Identity:** GSSOC Contributor

**Closes:** #594

---

### Description of Changes 📃

I have added a project which uses the K-means clustering algorithm on mall customers' data to segment them. The project involves data preprocessing, applying the K-means algorithm, and visualizing the clusters.

---

### Type of Change ☑️

- [x] New project (non-breaking change which adds functionality)

---

### How Has This Been Tested? ⚙️

I tested it on my local system.

---

### Checklist ☑️

- [x] My code follows the Contributing Guidelines & Code of Conduct of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.

---

### Screenshots 📷
output

---

### Note to Reviewers 📄

I have resolved the conflicts and made a new pull request. Kindly go through it.

**Comment by invigorzz313** [comment]
> Also in this PR, there are commits of other files unrelated to the objective

Please look into this. There are other files with changes in your commit, apart from K-Means Clustering Algorithm folder.

**Pull request closed without merging**
