### PR TITLE
Deepfake Video Detection

### PR DESCRIPTION
**Pull request by AbheetHacker4278**
@Niketkumardheeryan please Review this PR and merge it with master branch , hope you like it 

and the model folder are empty because the Github is accepting only 25mb og files but mine was of **200mb+** due to this i am unable to upload those file , after merging with master branch i can do that work also.

### Issue number

#867

### CODE REVIEW

**Comment by AbheetHacker4278** [comment]
@Niketkumardheeryan here i can provide the links for Models , which i have kept in google drive due to size issue.

https://drive.google.com/drive/folders/12L8bQnHt_X1sfoOIXrssPzSoi2cGcKU4?usp=drive_link

**Comment by AbheetHacker4278** [comment]
@Niketkumardheeryan please assign this me under gssoc24 and with level label

**Comment by AbheetHacker4278** [comment]
Okay i will do it

**Comment by Niketkumardheeryan** [comment]
@AbheetHacker4278 any update on this

**Comment by AbheetHacker4278** [comment]
> @AbheetHacker4278 any update on this

Sorry for inconvenience,  because i have my college semester exams , i was busy very much , till tommorow i complete my whole work

**Comment by AbheetHacker4278** [comment]
@Niketkumardheeryan i have made the folder public  , please check

**Pull request merged**
