### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Saksh8**

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
@Saksh8  please add Readme.md file with PR, and  Use matplotlib or seaborn or any other libraries for Visual analytics of data before creating the ML Model.

**Comment by Saksh8** [comment]
Alright Sir, I will do the same

**Comment by Saksh8** [comment]
I have updated the project with ReadMe Section and Data Visualization Section in the Prediction Model

**Comment by khushi-igupta** [comment]
Hello @invigorzz313 I am a GsSOC'24 contributor and I would like to work on this issue. Can you please assign it to me?

**Pull request merged**
