### PR TITLE
Student marks prediction model has been added

### PR DESCRIPTION
**Pull request by AkhilYadavPadala**
#544 issue is solved

### CODE REVIEW

**Comment by AkhilYadavPadala** [comment]
@invigorzz313 
Review changes and add level (1,2,3)

**Comment by invigorzz313** [comment]
Please deploy the ML model or integrate it into a web app.

**Comment by Niketkumardheeryan** [comment]
hi @AkhilYadavPadala  , as you know there are lots of simple model in this so are expecting to you to deploy it, Please do the needful other we will not be able to merge your PR 

OR

you can create some other issues.
Happy coding

**Comment by AkhilYadavPadala** [comment]
Thanks for reviewing my PR @Niketkumardheeryan @invigorzz313 
Shall I use streamlit or modelbit to deploy?

**Comment by AkhilYadavPadala** [comment]
@Niketkumardheeryan @invigorzz313 
I've deployed my ML model with the method API deployment using modelbit. Please review it. 
Kindly, merge this PR under level(1/2/3).
I'll be happy if you labelled this PR as level 2

**Comment by Niketkumardheeryan** [comment]
hey @AkhilYadavPadala  Please make a PR IN capsule 1.1 Branch as we have a conflict in master Branch,  And please add steps of deployment of model in Readme.md file

**Pull request closed without merging**
