### PR TITLE
Added Disease_prediction

### LINKED ISSUE #661: Add Diseases Perdiction model which also gives prescriptions
Based on the provided symptoms from the user, our model will predict what disease our user is suffering from and give prescriptions based on that. It can classify the most common diseases and prescribe the most accurate suggestions based on the disease.
Please assign this issue to me @Niketkumardheeryan

### PR DESCRIPTION
**Pull request by Kyouma45**
According to the symptoms provided by the user, the model takes over 130 inputs to predict 40+  diseases correctly and gives prescriptions to the user based on the expected disease. The model has over 97.6% accuracy score.
Fixes #661

### CODE REVIEW

**Comment by Kyouma45** [comment]
Sir @Niketkumardheeryan,

Input consists of 133 different symptoms.
image


Output is one of the 40 Diseases.
image


With accuracy over 97.6%.
image

I have integrated the model with LLM to provide prescriptions.

Example:
image

**Comment by invigorzz313** [comment]
@Kyouma45 Please add a detailed ReadMe.md file.

**Comment by Kyouma45** [comment]
I have done sir @Niketkumardheeryan. Please review.

**Comment by Kyouma45** [comment]
@Niketkumardheeryan Done sir.

**Comment by Kyouma45** [comment]
@Niketkumardheeryan sir, I have updated the readme file. please review it.

**Comment by Kyouma45** [comment]
@Niketkumardheeryan sir, Sorry to disturb you repeatedly, but I have finished working on the task. Please review the PR. Also, please sir can you add level label as well on both issue #661 and PR #694  I apologize for asking for it numerous times but the Program Manager posted this,

"We are in the final stage of leaderboard updates.
I noticed few things PA's not mentioned lables on PR.
like gssoc, level1, level2, level3
gssoc24,GSSoC'24, gssoc
These are the labels.
with level1,level2, level3
recommended to use gssoc. Make sure this is assigned to issues and PR as well."

**Comment by Kyouma45** [comment]
@Niketkumardheeryan Sir, Please review the request

**Comment by Kyouma45** [comment]
@Niketkumardheeryan Sir, Please review the PR.

**Comment by sanjay-kv** [comment]
@invigorzz313 Why this is pending for a long, please let contributor if anything need to be done.

**Pull request merged**
