### PR TITLE
Image Stitching Project using OpenCV library

### LINKED ISSUE #846: Image Stitching using OpenCV library
Proposal to add a segment which teaches about using OpenCV library for stitching two or more images to create a panorama-like effect.
It will have a documentation and running code. This feature is a part of a larger subject of image processing and Machine Learning, therefore I feel it is worth it, for it to be a part of this project.

Kindly review my proposal and please assign this to me under GSSOC'24. Thank you.

### PR DESCRIPTION
**Pull request by Aryan-Chharia**
Dear admin, I have created the Image Stitching Project folder which has the code for image stitching, dataset required and also a readme file for better understanding. Kindly review it and please let me know if any changes have to be made. Also can you assign level as well along side GSSoC'24 tag ?

Closes #846

### CODE REVIEW

**Comment by invigorzz313** [comment]
@Aryan-Chharia Avoid .py files, instead use .ipynb file with multiple cells and proper commenting

**Comment by Aryan-Chharia** [comment]
Ok I will make the changes and then commit it again.

**Comment by Niketkumardheeryan** [comment]
@Aryan-Chharia Good work just , Execute each cell must have a proper output. And make same changes in readme.md file

**Comment by Niketkumardheeryan** [comment]
@Aryan-Chharia ??

**Comment by Aryan-Chharia** [comment]
@Niketkumardheeryan Hello, sorry for not replying back. I got busy with my job. I have checked the program thoroughly. Most of the cell are just importing the files or are creating the functions.

The main function / cell which is creating the final stitched image, is doing two things -

1.) writing the image in the results folder on the disk
2.) also showing the image to the using using cv2.show function

Due to cv2.show function the image is displayed in a separate window rather than below the cell. I have already added the output images in the readme file of the two images that will be generated in the process. Can you tell me more what I have to do on this ?

**Pull request merged**
