### PR TITLE
Dark pattern detection added

### PR DESCRIPTION
**Pull request by litesh1123**
Sir as proposed i have added dark pattern detection feature ,this will help users detect dark patterns in e-commerce websites .If possible please assign label-3 to this issue it will be helpful to me and as i have implemented new technologies like ocr software for text extraction unlike traditional manner i have sent demo video drive link in linkedin please checkout i have some other feature ideas which will make it more interactive if u like this work i will propose those ideas too.

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
@litesh1123 add readme.md file and explain what is the project about and steps involved ,and add SS of results in readme.md file.

**Comment by litesh1123** [comment]
Okay sir i will create readme, 
@Niketkumardheeryan are all other things related to project approved or any issue with it sir

**Comment by litesh1123** [comment]
@Niketkumardheeryan sir, I have updated the readme with all the details regarding dark patterns, their importance, and their impact, but I was unable to add ss to the readme. Md file while raising a pull request I have attached a working demo drive link and screenshots please check it out, sir.

**Comment by litesh1123** [comment]
@Niketkumardheeryan thank you sir , if possible please assign label 2 to this issue sir or else this merge won't be counted it's my humble request
I have raised issue for addition of gui interface for dark patterns sir please assign issue to me

**Pull request merged**
