### PR TITLE
Chi-Square Test 

### LINKED ISSUE #848: Chi-Square Test
The Chi-Square Test is a statistical method used to determine if there is a significant association between categorical variables. It compares the observed frequencies of categorical data with the frequencies that would be expected if the variables were independent. The test calculates a Chi-Square statistic, which measures the difference between observed and expected frequencies under the null hypothesis of independence. It is widely used in fields such as biology, social sciences, and market research to assess relationships between variables without assuming a specific distribution of the data.
Used for categorical data to assess how likely it is that an observed distribution is due to chance.

1. Chi-Square Goodness of Fit Test: Tests if a sample matches a population.
2. Chi-Square Test for Independence: Tests if there is a significant association between two categorical variables.

### PR DESCRIPTION
**Pull request by ranamanish674zu**
fixes #848  
@Niketkumardheeryan , @invigorzz313 i complete #848 can you please review

### CODE REVIEW

**Comment by invigorzz313** [comment]
@ranamanish674zu The Readme.md must be properly written in a markdown format.
And there is a .docx file, remove that if not needed.

**Comment by ranamanish674zu** [comment]
@invigorzz313 i had a doc file so i remove the readme.md file , now could you please reivew

**Comment by invigorzz313** [comment]
@ranamanish674zu Readme.md is mandatory and in markdown language. 
.docx file is not supported as Readme.md

**Comment by ranamanish674zu** [comment]
@invigorzz313 now i modified the readme.md file , can you please check now

**Comment by invigorzz313** [comment]
@ranamanish674zu just remove the .docx file and is good to go

**Comment by ranamanish674zu** [comment]
@invigorzz313  now i modified as you said , can you review now

**Pull request merged**
