### PR TITLE
Added Crude oil forecasting

### LINKED ISSUE #939: Add Crude oil forecasting
The Crude Oil Forecasting project aims to predict future prices of crude oil using advanced machine learning and statistical techniques. Accurate forecasting of crude oil prices is critical for stakeholders in the energy sector, including producers, traders, and policymakers, as it helps in making informed decisions about production, investment, and policy.

### PR DESCRIPTION
**Pull request by pavitraag**
Added Crude oil forecasting
closes #939

### CODE REVIEW

**Comment by pavitraag** [comment]
@invigorzz313 please merge this

**Comment by Niketkumardheeryan** [comment]
@pavitraag good work, but your readme.md file doesn't match with .ipynb files' code ,you have written
1. Data fetch from api (no such code found )
2. You are using file.upload() - not used in code
3. In your readme.md file you have written Model selection - doesn't found any comparision between different Models.

**Comment by Niketkumardheeryan** [comment]
Also add in your readme.md file that why have you used these different visualization plots and what's the impact of these plots in code.

**Comment by pavitraag** [comment]
@Niketkumardheeryan @invigorzz313 done with changes

**Pull request merged**
