### PR TITLE
Music generation

### PR DESCRIPTION
**Pull request by Soubeer**
In this project, I developed a music generation model to create new musical compositions. By training the LSTM model on a dataset of MIDI files, it learns the sequences and patterns inherent in the music. This enables the model to generate original music pieces that mimic the style and structure of the training data, showcasing the potential of networks in creative applications such as automated music composition and music style emulation.

It uses the GTZAN dataset , which is very useful and effective in this scenario, it is very large in size hence cannot be added to a repo but anyone can access it from 
https://www.kaggle.com/datasets/andradaolteanu/gtzan-dataset-music-genre-classification

It gives out generated music according to personal preference and likings of the user keeping in mind the qualities that the user demands.

Fixes#551

### CODE REVIEW

**Comment by Soubeer** [comment]
@invigorzz313 can you check this PR? Its done

**Comment by Niketkumardheeryan** [comment]
Hi @Soubeer ,great work but try to use more cells for writing your code and use h2 heading for  readable code in your .ipynb .
ANd add result in you reame.md file

**Comment by Soubeer** [comment]
@Niketkumardheeryan Sir, the code is labelled with comments at every cell..if I break it more , it will be more confusing to understand.

and for the results,it is in audio format, so it cannot be inserted in readme but is present immediately at position when the .ipynb file is opened.

**Comment by Soubeer** [comment]
@Niketkumardheeryan can you check my task pls ? I have provided the reasons for the changes you asked me.

**Comment by Niketkumardheeryan** [comment]
@Soubeer you can use a cell for particular functions and comment accordingly,
And please download generated sound and attach in readme,

**Comment by Soubeer** [comment]
@Niketkumardheeryan Made both the changes-Made different cells for diff functions but had to keep the classes together else they wont work..but both have comments.

Added audio files in MOV format in readme

**Pull request merged**
