### PR TITLE
Keyframes_Extraction_and_Object_Detection(for that key frame) 

### PR DESCRIPTION
**Pull request by omkar806**
Description - So this is my project all about the key frames extraction from a particular video and saving it with the timestamp into a folder and then performing the object detection using YOLO V3 Model for each key frame and also givinig the count for the maximum number of objects present in which key frame .

### CODE REVIEW

**Comment by omkar806** [comment]
I accidently created another pull request but now I have added the Demo video too with all the steps mentioned in detail in the readme.md file ... please let me know if there are any changes required

**Comment by omkar806** [comment]
Actually in the previous pull request the branch that I had created , So in that branch I had pushed a demo video greater than 100 mb so now I am not able to push a new video as it is saved in thae git history so I created a new branch instead and pushed the demo video ...

**Comment by Niketkumardheeryan** [comment]
> Actually in the previous pull request the branch that I had created , So in that branch I had pushed a demo video greater than 100 mb so now I am not able to push a new video as it is saved in thae git history so I created a new branch instead and pushed the demo video ...

hey just show less output np array in your .ipynb file( -- )  and your readme.md file  try to make some changes to it to make it attractive

**Comment by Niketkumardheeryan** [comment]
> Yeah I have removed the np array outputs from my .ipynb file and also I will make some changes in readme.md file

@subhadeeppaul ur views on it

**Comment by Niketkumardheeryan** [comment]
> Yeah I have removed the np array outputs from my .ipynb file and also I will make some changes in readme.md file

can't see ur changes

**Pull request closed without merging**
