### PR TITLE
Issue#347 Language Detection

### PR DESCRIPTION
**Pull request by RusJaI**
Language Detection pipeline along with preprocessing, feature extraction, classification. 
Achieved an accuracy of 97.3%

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
hey, @RusJaI Great work, but just print only  1 or 2 elements of the list, Ex - list_nabme[1:2] ,  you have printed the whole list in your code ...

And show at least one output...

**Comment by RusJaI** [comment]
> 

Okay sure!

**Comment by Niketkumardheeryan** [comment]
> > 
> 
> Okay sure!

mention the issue as well

**Comment by RusJaI** [comment]
@Niketkumardheeryan can you merge this issue?

**Pull request merged**
