### PR TITLE
Duplicate question Pair Using NLP end To end Project

### PR DESCRIPTION
**Pull request by pawansharma197**
Made a Project using data set provided by Quora during their contest . There are 3 Jupyter Notebook one with simple implementation of Random Forest Algorithm that have an Accuracy of 75% , another with feature Engineering  . There are total 7 new Feature that are added . and then trained model using Random Forest .

Built  an End to end project using StreamLit . 
So For Running The Project Run Python Notebook  first , data set Train.csv is already provided and then install the following dependency provided in Requirement Section to run The application and get the desired Result .

As The data set is Too Long about 400005 so Be paitent while running python notebook .

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
@pawansharma197 maintain the proper readme.md file, explain your file workflow as you have explained above ...

**Comment by pawansharma197** [comment]
Okay

**Comment by pawansharma197** [comment]
Can I change my Readme file here only or I have to make a pull request again

**Comment by pawansharma197** [comment]
Readme File mai changes kar diyai h plz check

**Comment by Niketkumardheeryan** [comment]
> Readme File mai changes kar diyai h plz check

add link of your web app in the readme.md file  (By creating a result section in your readme.md file ) for this you can refer others' notebooks for proper headings in the readme.md file

**Review by subhadeeppaul — COMMENTED** [review]
Is it already deployed? If yes, then please attach the link in the readme file.

**Comment by pawansharma197** [comment]
> Is it already deployed? If yes, then please attach the link in the readme file.

No It is Not Deployed That why I have not pasted the Link in Readme

**Comment by Niketkumardheeryan** [comment]
> > Is it already deployed? If yes, then please attach the link in the readme file.
> 
> No It is Not Deployed That why I have not pasted the Link in Readme

Then from where you have attached these images

**Comment by pawansharma197** [comment]
> > > Is it already deployed? If yes, then please attach the link in the readme file.
> > 
> > 
> > No It is Not Deployed That why I have not pasted the Link in Readme
> 
> Then from where you have attached these images
Run This Command
Streamlit run app.py , Your web application will be running on Localhost

**Pull request merged**
