### PR TITLE
Add Content: Pandas Basics 

### PR DESCRIPTION
**Pull request by kRiShNa-429407**
I am added two topics:

1. Introduction to Pandas and DataFrames.
2. Importing and exporting data in Pandas.

I will add content topic wise so it's quite easy to learn.

my issue no is #653

please review and approve

### CODE REVIEW

**Comment by kRiShNa-429407** [comment]
please review and approve

**Comment by invigorzz313** [comment]
@kRiShNa-429407 Please add a detailed ReadMe.md file.

**Comment by Niketkumardheeryan** [comment]
hi @kRiShNa-429407 , 
1. there is no readme.md  - Add reamed.md first ->its all about what the content about.
  2. There is only  basics imports and data types and all ,please try to utilize  more Function of pandas -like type of visualization provided by Pandas and more Depth function fro statistical Analysis,

you just add the contain that mostly project have in this repo, try to improve it and follow above instruction .

**Comment by kRiShNa-429407** [comment]
Okk sir
I started it from very basic and take it to advance.

**Comment by kRiShNa-429407** [comment]
Ok i am adding readme.md file

**Comment by kRiShNa-429407** [comment]
Please review now🙏

**Pull request merged**
