### PR TITLE
Improved Flight_delay_prediction_project

### PR DESCRIPTION
**Pull request by FreeSpirit11**
To enhance the performance of the flight delay prediction model, I have made the following changes:

**1. Implemented Advanced Models:**
Trained and evaluated models like Random Forest, Gradient Boosting, and LSTM.

**2.Did Hyperparameter Tuning:**
Utilized GridSearchCV or RandomizedSearchCV to perform hyperparameter tuning for the selected models.

**3.Evaluated Performance:**
Compared the performance of these models with the current Decision Tree model using appropriate metrics like ROC AUC score.

### CODE REVIEW

**Comment by FreeSpirit11** [comment]
Resolves #611 .

**Comment by FreeSpirit11** [comment]
Hi @invigorzz313 , this is not a level 1 task . Atleast mark it level 2 please.

**Comment by sudiptasarkar011** [comment]
i would like to work on this issue, can you please assign this to me?

**Comment by Niketkumardheeryan** [comment]
> Hi @invigorzz313 , this is not a level 1 task . Atleast mark it level 2 please.

HI @FreeSpirit11 , I just reviewed your code and found that no null values handling, and no outliers handling  , NO data analysis before using data, how can you saythat its a Level 2 work.
And you define the levels ,we are here for that.

**Comment by FreeSpirit11** [comment]
Hi @Niketkumardheeryan ,As mentioned in the issue, my focus was specifically on implementing advanced models, hyperparameter tuning, and performance evaluation. These tasks were clearly required a good level of coding and understanding of the machine learning workflow.

Level 1 are the tasks which don't require coding or just require simple coding like null values handling. But still if you consider it a level 1 task then it's fine . :)

I understand the importance of comprehensive data preprocessing and analysis. If additional  tasks such as handling missing values, outlier detection, or more detailed data analysis are required, I am more than willing to address these. However, having clear and specific requirements from the beginning would ensure that the project meets all expectations without any misunderstandings.

**Pull request closed without merging**
