### PR TITLE
Bird Species Claassificatin & model deployment

### PR DESCRIPTION
**Pull request by shreya024**
Related issue : #355 

I am unable to upload the .h5 file because it exceeds size limit. Kindly guide me how to compress a .h5 file.
Link to the webapp : https://share.streamlit.io/shreya024/bird-species-classification-web-app/app.py

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
> Related issue : #355
> 
> I am unable to upload the .h5 file because it exceeds size limit. Kindly guide me how to compress a .h5 file. Link to the webapp : https://share.streamlit.io/shreya024/bird-species-classification-web-app/app.py

If your app is working properly then you can attach link of google drive by uploading your model.h5 on it...

**Comment by Niketkumardheeryan** [comment]
@shreya024 in your readme.md file add snip of your app not others' app (it is showing Bitcoin prediction)and write the proper heading, And run all cells of .ipynb file and then reupload it..

**Comment by shreya024** [comment]
> @shreya024 in your readme.md file add snip of your app not others' app (it is showing Bitcoin prediction)and write the proper heading, And run all cells of .ipynb file and then reupload it..

I have added my snips only (I can see pics of two birds)...And sure I will make the other changes

**Comment by shreya024** [comment]
> > Related issue : #355
> > I am unable to upload the .h5 file because it exceeds size limit. Kindly guide me how to compress a .h5 file. Link to the webapp : https://share.streamlit.io/shreya024/bird-species-classification-web-app/app.py
> 
> If your app is working properly then you can attach link of google drive by uploading your model.h5 on it...

I have done all the requested changes. Kindly check now

**Comment by shreya024** [comment]
@Niketkumardheeryan Thank you so much for merging :) .Kindly add GSSoc22 label

**Pull request merged**
