### PR TITLE
Added: Maternal Health Risk Prediction

### LINKED ISSUE #974: Add: Maternal Health Risk Prediction
I want to add a Maternal Health Risk Dataset Classidfication Model which is built using Machine Learning.

### PR DESCRIPTION
**Pull request by kosuri-indu**
Added the maternal health risk prediction analysis and model
Closes #974 

https://github.com/user-attachments/assets/3ded396f-4a3d-4e51-bb8c-784cd4d665d3

### CODE REVIEW

**Comment by kosuri-indu** [comment]
@invigorzz313 @Niketkumardheeryan 
Please review and merge this PR 
Thank you

**Comment by Niketkumardheeryan** [comment]
@kosuri-indu improve readme.md file and Depliyour model , as these kind of simple model already there ,so you have deploiit..

**Comment by kosuri-indu** [comment]
@Niketkumardheeryan yes sir, i have deployed it and added respective file

**Comment by invigorzz313** [comment]
@kosuri-indu 
the deployment does not seem authentic (video). 
Many warnings in the code.
Code is distributed in too many cells unnecessarily.

**Comment by kosuri-indu** [comment]
@invigorzz313 
yes ma'am, removed the warnings in the code and consolidated it.

**Pull request merged**
