### PR TITLE
GSSOC '24 : Added Perform-Modelling-on-Ionosphere-Dataset 

### PR DESCRIPTION
**Pull request by sujanrupu**
### Project Description:
The following project aims to predict class using various technical specifications (features) as input to the logistic regression algorithms.

Issue : #599

### CODE REVIEW

**Comment by sudiptasarkar011** [comment]
I have a keen interest in data science and would like to work on this, could you please assign this to me?

**Comment by sujanrupu** [comment]
@invigorzz313 please review the PR

**Comment by Niketkumardheeryan** [comment]
@sujanrupu you have to add readme.md file in this project, don't change ML capsule readme.md file .

**Comment by Niketkumardheeryan** [comment]
@sujanrupu any update from your side,otherwise close it soon.

**Comment by Niketkumardheeryan** [comment]
Please Make another PR ,when are available as your PR has a conflict as well

**Pull request closed without merging**
