### PR TITLE
Spelling Corrector Added

### PR DESCRIPTION
**Pull request by shreya024**
Related Issue: #365 

#### LINK TO WEBAPP:

https://share.streamlit.io/shreya024/spellcorrector/main/app.py

#### GLANCE AT THE WEBAPP

https://user-images.githubusercontent.com/72400676/162678085-b57daf9c-cadb-43a8-af65-9e2b46dfe4d0.mp4

#### MODELS USED

Sequence to Sequence Encoder-Decoder Model - 99.12 % accuracy

I have mentioned all the important links in the README

### CODE REVIEW

**Review by Rutikab12 — APPROVED** [review]
Well Done !

**Comment by Niketkumardheeryan** [comment]
@shreya024 I know, you have copy-pasted some functions in your code, that is fine but at least add a reference in the readme.md file

**Comment by Niketkumardheeryan** [comment]
> @shreya024 I know, you have copy-pasted some functions in your code, that is fine but at least add a reference in the readme.md file

@pratishthaa @Rutikab12 what are your views on it ...

**Review by Rutikab12 — APPROVED** [review]
Good. If you are using any prebuilt code , always add reference for that work.

**Comment by shreya024** [comment]
> Good. If you are using any prebuilt code , always add reference for that work.

Okay :)

**Comment by shreya024** [comment]
> @shreya024 I know, you have copy-pasted some functions in your code, that is fine but at least add a reference in the readme.md file

I have added the reference

**Pull request merged**
