### PR TITLE
SQL.md added to cheat sheets

### PR DESCRIPTION
**Pull request by Tanuj-rai**
I have added the cheat sheet pdf for SQL and also add some resources for it in response to Issue #333

### CODE REVIEW

**Comment by Tanuj-rai** [comment]
@Rutikab12 I have created this PR can you please give me feedback regarding it so that I can improve if anything needs to be changed.

thank you

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
Changes are okay.
But if you can enhance it more with different links and images, it will be good. 
Try to add these parts in md file.

**Comment by Tanuj-rai** [comment]
ok I will add more resources and images

> Changes are okay. But if you can enhance it more with different links and images, it will be good. Try to add these parts in md file.

ok, I will add more resources and images to it.

**Comment by Niketkumardheeryan** [comment]
> > Changes are okay. But if you can enhance it more with different links and images, it will be good. Try to add these parts in md file.
> 
> ok, I will add more resources and images to it.

hey add more details and create a proper cheat sheet means a write short notes as well ....

**Pull request closed without merging**
