### PR TITLE
Fish Weight Estimation 

### PR DESCRIPTION
**Pull request by shivam-s16**
@Niketkumardheeryan Completed on issue 258 please check it out and if there is some correction please let me know.
It fixes https://github.com/Niketkumardheeryan/ML-CaPsule/issues/258

### CODE REVIEW

**Review by pratishthaa — CHANGES_REQUESTED** [review]
Please mention highest accuracy and the model it is for, in Readme file

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
Mention the issue name instead of the candidate name in PR's title. 
and mention the accuracies you got with the algorithm used in the README file.

**Comment by shivam-s16** [comment]
@pratishthaa @Rutikab12 Check it out once and inform for any changes .

**Comment by shivam-s16** [comment]
@pratishthaa @Rutikab12 @Niketkumardheeryan Please check it out by mistake 2 issues are merge together please check it out and inform for any changes .
Issues are #245 and #258

**Comment by Niketkumardheeryan** [comment]
> @pratishthaa @Rutikab12 @Niketkumardheeryan Please check it out by mistake 2 issues are merge together please check it out and inform for any changes . Issues are #245 and #258

Delete these files and reupload them separately ()

**Comment by Rutikab12** [comment]
> @pratishthaa @Rutikab12 @Niketkumardheeryan Please check it out by mistake 2 issues are merge together please check it out and inform for any changes . Issues are #245 and #258



> @pratishthaa @Rutikab12 @Niketkumardheeryan Please check it out by mistake 2 issues are merge together please check it out and inform for any changes . Issues are #245 and #258

Reupload files and make two separate PR's for the same. @shivam-s16

**Pull request merged**
