### PR TITLE
Bitcoin Price Prediction Web App

### PR DESCRIPTION
**Pull request by tandrimasingha**
Issue Title: Bitcoin Price Prediction Web App
Issue no: #217 
Description: Developed a Web App that predicts the price of bitcoin with 99% accuracy.
Link to WebApp: [WebApp Link here](https://share.streamlit.io/tandrimasingha/bitcoin-price-prediction-web-app/main/app.py)
GSSOC'22 Participant

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
@tandrimasingha Great work, But Please add HTML and  CSS file as well and add Some information about cloud used for Model Deployment in the readme.md file with some snapshots of your results...

Additional (you can igone it) : - ->And your model is overfitted that's why it is showing 99 % accuracy..

**Comment by Niketkumardheeryan** [comment]
@tandrimasingha Great work, But Please add HTML and  CSS file as well and add Some information about cloud used for Model Deployment in the readme.md file with some snapshots of your results...

Additional (you can igone it) : - ->And your model is overfitted that's why it is showing 99 % accuracy..

**Comment by tandrimasingha** [comment]
Thank you sir , I will add some pictures of my web app but Sir I didnot use HTML and CSS rather I used only streamLit Share to deploy my model...

**Comment by Niketkumardheeryan** [comment]
> Thank you sir , I will add some pictures of my web app but Sir I didnot use HTML and CSS rather I used only streamLit Share to deploy my model...


Then Write something about streamlit share ...

**Comment by tandrimasingha** [comment]
@Niketkumardheeryan Sir, I have made the changes required. Please merge it .

**Comment by tandrimasingha** [comment]
> > Thank you sir , I will add some pictures of my web app but Sir I didnot use HTML and CSS rather I used only streamLit Share to deploy my model...
> 
> Then Write something about streamlit share ...

@Niketkumardheeryan Sir, I have added info about streamlit share. I hope its okay now.

**Pull request merged**
