### PR TITLE
Analyze Glassdoor data

### LINKED ISSUE #325: Analyze Glassdoor data
https://www.kaggle.com/nilimajauhari/glassdoor-analyze-gender-pay-gap

### PR DESCRIPTION
**Pull request by urvisinghal**
closes #325

### CODE REVIEW

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
Please comment the code in ipynb file to easily understand what points you have discovered from the analysis of data.

**Comment by UrviSinghal28** [comment]
> Please comment the code in ipynb file to easily understand what points you have discovered from the analysis of data.

hey is it okay now?

**Comment by Rutikab12** [comment]
> > Please comment the code in ipynb file to easily understand what points you have discovered from the analysis of data.
> 
> hey is it okay now?

yes now its fine

**Comment by Niketkumardheeryan** [comment]
@UrviSinghal28 check your readme.md file , you have added stock price analysis change it

**Comment by UrviSinghal28** [comment]
> @UrviSinghal28 check your readme.md file , you have added stock price analysis change it

Hey corrected now, sorry for the issue

**Pull request merged**
