### PR TITLE
Added SQL injection detection folder

### PR DESCRIPTION
**Pull request by Chhaya-g**
Aim: The aim of the problem statement is to develop a CNN model for SQL injection detection. I have used a huge dataset from Kaggle(68,000 rows) consisting of user input along with a label. I have trained a simple CNN model as well as a 2D CNN model to solve the problem.
@Niketkumardheeryan, To solve the problem, I added a SQL injection detection Folder with seven files readme.md, cnn.md, requirements.txt, image.png, mergecsv.csv, SQLID.ipynb, SQLinjectiondetection2DCNN.ipynb.
readme.md,  image.png and cnn.md have all the necessary description about the problem and its various aspects and the underlying technique used to solve the problem.
requirements.txt contains all the requirements to run this project on a local machine.
SQLID.ipynb and SQLinjectiondetection2DCNN.ipynb contains the main model used for the problem along with all the data preprocessing and feature extraction.
Here I have used both CNN and 2D CNN for solving the problem. Kindly, look into it @invigorzz313 

closes: #776

### CODE REVIEW

**Comment by Chhaya-g** [comment]
@Niketkumardheeryan @invigorzz313 kindly check my pull request which I had opened last week in response to getting an issue assigned to me under GSSOC'24.

**Comment by Niketkumardheeryan** [comment]
@Chhaya-g add more cells in your code , for better readability and add more comments as well . Use proper heading in readme.md file with results of your model.

**Comment by Chhaya-g** [comment]
> @Chhaya-g add more cells in your code , for better readability and add more comments as well . Use proper heading in readme.md file with results of your model.

okay, I will get back to you asap.

**Comment by Chhaya-g** [comment]
@Niketkumardheeryan I have added more comments, improved the readability of the code as well as of the markdown files(readme.md & cnn.md) and also mentioned the results of the models in the readme.md file.
Also SQLinjectiondetection2DCNN.ipynb is the main jupyter notebook with all the steps(data preprocessing and feature engineering) with comments and the other jupyter notebook just has few  more main models, as all the prior steps are just the same.
Kindly, check my commit and merge it under GSSOC'24. Also please assign a necessary level label (level-2 or level-3).

**Pull request merged**
