### PR TITLE
Issue #436 Naive Bayes Classifier

### PR DESCRIPTION
**Pull request by Neha-Niharika-Kar**
I have made the documentation on Naive Bayes Classifier algorithm.
Kindly check it.

### CODE REVIEW

**Review by pratishthaa — CHANGES_REQUESTED** [review]
Add references

**Comment by Neha-Niharika-Kar** [comment]
I have to create a new PR with the changes?

**Comment by pratishthaa** [comment]
Make changes in same PR

**Comment by Neha-Niharika-Kar** [comment]
Please check now

**Comment by pratishthaa** [comment]
@Rutikab12 @Niketkumardheeryan what do you guys think?

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
It will be great if you add one theory example below Bayes Theorem and explain working of classifier with the dataset you used.

**Comment by Neha-Niharika-Kar** [comment]
Okay sure.

**Comment by Neha-Niharika-Kar** [comment]
Check now if it's okay.

**Review by Rutikab12 — APPROVED** [review]

**Comment by Niketkumardheeryan** [comment]
> Check now if it's okay.

Hey , your notebook is filled with np array correct them and you can add comments in the middle as well for better understanding and add readme.md too.

**Comment by Neha-Niharika-Kar** [comment]
> > Check now if it's okay.
> 
> Hey , your notebook is filled with np array correct them and you can add comments in the middle as well for better understanding and add readme.md too.

Anything wrong with np arrays? Data is extracted in that format only.

**Review by Rutikab12 — APPROVED** [review]

**Comment by Neha-Niharika-Kar** [comment]
Please check now

**Pull request merged**
