### PR TITLE
arranged the necessary  documentations into categories 

### PR DESCRIPTION
**Pull request by NIKITA320495**
arranged the available documentation and content  into 3 categories _machine learning , _deep learning and _data science . it simplifies the learning and this folders keeps the content which is different from projects so that one can learn from it. it also makes it easier for others to add necessary content and documentation as well

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
hi @NIKITA320495 , good work, can you please ensure that nothing left in all folders, please please create A PR for New Branch (Capsule 1.1).

You can take help from @invigorzz313 , if you get stuck anywhere ,

**Comment by NIKITA320495** [comment]
@Niketkumardheeryan yes sir i am trying it again and will arrange the documentations so they may appear differently from the project

**Comment by NIKITA320495** [comment]
@invigorzz313 i am having some doubts regarding this

**Comment by NIKITA320495** [comment]
@invigorzz313 should i proceed with a PR again or should i arrange the folders again ??

**Comment by invigorzz313** [comment]
@NIKITA320495 You must create a PR again as you have to commit to the Capsule 1.1 branch of this repo.

Also, in your forked and cloned repo, you need to create a new branch for a new PR (here, you committed directly from master) and then push your changes from the new branch to the Capsule 1.1 branch of this repo.

**Comment by Niketkumardheeryan** [comment]
hi @NIKITA320495 , you need to create a new PR now , as this has a conflict in master Branch.

**Pull request closed without merging**
