### PR TITLE
Sentiment Analysis for Depression based on Social Media Posts #265

### PR DESCRIPTION
**Pull request by 0ddoes**
Python Notebook and Readme file added. Please Review it and let me know if I need to make any edits.

### CODE REVIEW

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
Please re-check the files you have uploaded.

**Comment by 0ddoes** [comment]
Edited. Please check the files.

**Comment by 0ddoes** [comment]
Should I mention in Readme? The Issue is #265

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
Please make separate PR for different projects.

**Pull request merged**
