### PR TITLE
Added Movie Revenue Prediction System

### PR DESCRIPTION
**Pull request by Vikranth3140**
Hello,

This PR is with respect to Issue #725 and I have added Movie Revenue Prediction using ML Libraries.

The datasets have been taken from [Movie Industry](https://www.kaggle.com/datasets/danielgrijalvas/movies) dataset.
Detailed instructions on how to set up our datasets are provided in [old datasets\README.md](old%20datasets/README.md).

I have used different models and the accuracies are as follows:

| Model           | Training R² | Training MAPE | Testing R² | Testing MAPE |
|-----------------|-------------|---------------|------------|--------------|
| Linear Regression | 0.6553      | 35.23%        | 0.6706     | 18.49%       |
| Decision Tree     | 0.8664      | 13.00%        | 0.6947     | 4.60%        |
| Bagging           | 0.8583      | 13.32%        | 0.7719     | 5.67%        |
| Gradient Boosting | 0.9158      | 10.57%        | 0.8242     | 5.69%        |
| XGBoosting        | 0.9079      | 9.70%         | 0.8102     | 5.53%        |
| Random Forest     | 0.8728      | 14.29%        | 0.7786     | 5.33%        |

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
@Vikranth3140 cant find your file in PR , add a proper folder .

**Comment by Vikranth3140** [comment]
> @Vikranth3140 cant find your file in PR , add a proper folder .

I have added it as a submodule, as if i drop the files, it will not show up as the git modules will conflict

**Comment by Vikranth3140** [comment]
@Niketkumardheeryan pelase let me know the review as soon as possible

**Comment by invigorzz313** [comment]
@Vikranth3140 
You have to make the PR from a new branch instead of directly committing from the master branch. Then add the ReadMe.md, .ipynb file and other relevant files.

**Pull request closed without merging**
