### PR TITLE
Integratiion of Gradio as UI

### PR DESCRIPTION
**Pull request by AKing-283**
Hello PA and Mentor @invigorzz313  
I have integrated gradio which is a user friendly UI for ML applications. In this I have two text boxes one where user will insert the news and at the output the user will get to know whether it is real or fake. 

**Here is the Screenshot**
Screenshot 2024-05-25 at 5 31 50 PM

### CODE REVIEW

**Comment by AKing-283** [comment]
@invigorzz313  my another account @dp283 is also there as participants and I wasn't able to remove that account from VS code so I accidently made branch and uploaded changes from that account. But my main account is @AKing-283. I am sorry for this mistake 🙏🏼

**Comment by invigorzz313** [comment]
Please remove the commit of the main ReadMe.md file. You mustn't change that. And add a ReadMe.md for your project.

**Comment by invigorzz313** [comment]
It looks like you must first install the libraries necessary for running the notebook. As I notice errors  in many cell outputs due to absence of the required library.

**Comment by AKing-283** [comment]
yeah @invigorzz313 I made the changes in this ipynb file via colab and then I pushed it

**Comment by AKing-283** [comment]
> Please remove the commit of the main ReadMe.md file of the repo. You mustn't change that. And add about the new library used in the existing ReadMe.md of this project.

How should I do this changes ??. It's a little bit confusing

**Comment by invigorzz313** [comment]
> > Please remove the commit of the main ReadMe.md file of the repo. You mustn't change that. And add about the new library used in the existing ReadMe.md of this project.
> 
> How should I do this changes ??. It's a little bit confusing

When using git in your local machine, delete the commit from your log history where the main ReadMe.md is edited.

**Comment by AKing-283** [comment]
> > yeah @invigorzz313 I made the changes in this ipynb file via colab and then I pushed it
> 
> image
> 
> image
> 
> **These are some of the errors in the cell outputs that I notice in your commit. There are more of this.**
> 
> image
> 
> image
> 
> **Due to absence of required libraries in your notebook, there is no proper running of code.
> 
> and the code you added (the model), you did not run them at all.**
> 
> image
> 
> **The PR cannot be considered if all these are not rectified.**

@invigorzz313, I am doing this changes via colab and I am not able to clear these errors in vs but when I tried running it via colab it was running fine. Pls try to run this file file via colab once.

**Comment by AKing-283** [comment]
I tried to install the libraries via terminal in vs code but still facing same errors that's why I am making changes via colab

**Comment by AKing-283** [comment]
Screenshot 2024-05-30 at 1 40 43 PM
here it is the readme of original file and it is not changed

**Comment by invigorzz313** [comment]
> > > yeah @invigorzz313 I made the changes in this ipynb file via colab and then I pushed it
> > 
> > 
> > image
> > image
> > **These are some of the errors in the cell outputs that I notice in your commit. There are more of this.**
> > image
> > image
> > **Due to absence of required libraries in your notebook, there is no proper running of code.
> > and the code you added (the model), you did not run them at all.**
> > image
> > **The PR cannot be considered if all these are not rectified.**
> 
> @invigorzz313, I am doing this changes via colab and I am not able to clear these errors in vs but when I tried running it via colab it was running fine. Pls try to run this file file via colab once.

Unless your committed files have proper outputs finally, we cannot merge the PR. It would disturb the currently proper-output code.

**Comment by invigorzz313** [comment]
> Screenshot 2024-05-30 at 1 40 43 PM here it is the readme of original file and it is not changed

**I meant the main ReadMe.md file of this github repo.**
  
  

image

**Pull request closed without merging**
