### PR TITLE
Skin Disease Predictor Added

### PR DESCRIPTION
**Pull request by shreya024**
Related Issue: #387

### CODE REVIEW

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
@shreya024 Please upload the datasets to the dataset folder.
Also, give the title in ipynb file and explain some steps for better understanding.

**Comment by shreya024** [comment]
> @shreya024 Please upload the datasets to the dataset folder. Also, give the title in ipynb file and explain some steps for better understanding.

Okay sure I'll add more comments in the ipynb. As for the dataset, it is a 1.85 GB image dataset from kaggle https://www.kaggle.com/datasets/shubhamgoel27/dermnet .So I have provided link of the dataset in README. Should I download and add zip of the dataset?

**Comment by Rutikab12** [comment]
> > @shreya024 Please upload the datasets to the dataset folder. Also, give the title in ipynb file and explain some steps for better understanding.
> 
> Okay sure I'll add more comments in the ipynb. As for the dataset, it is a 1.85 GB image dataset from kaggle https://www.kaggle.com/datasets/shubhamgoel27/dermnet .So I have provided link of the dataset in README. Should I download and add zip of the dataset?

Okay Provide a link of it.

**Comment by shreya024** [comment]
> > > @shreya024 Please upload the datasets to the dataset folder. Also, give the title in ipynb file and explain some steps for better understanding.
> > 
> > 
> > Okay sure I'll add more comments in the ipynb. As for the dataset, it is a 1.85 GB image dataset from kaggle https://www.kaggle.com/datasets/shubhamgoel27/dermnet .So I have provided link of the dataset in README. Should I download and add zip of the dataset?
> 
> Okay Provide a link of it.

I have added more comments to ipynb along with title and link of the dataset is in README

**Pull request merged**
