### PR TITLE
Included Gradio UI

### PR DESCRIPTION
**Pull request by AKing-283**
Hello PA @Niketkumardheeryan  and collaorator @invigorzz313 
Here is my commit and pr with changes and the image of Gradio as UI. Please merge and label this pr if there are no issues in this pr. 😅
Screenshot 2024-06-01 at 10 36 11 AM

### CODE REVIEW

**Comment by invigorzz313** [comment]
Please tag the corresponding issue.
Include the file/changes in the appropriate project folder.

**Comment by AKing-283** [comment]
#562 is the issue

**Comment by AKing-283** [comment]
> Please tag the corresponding issue.
> Include the file/changes in the appropriate project folder.

Should I mention here the changes I made or is there any other way to do this

**Comment by AKing-283** [comment]
Included the file in which changes were made and here is the commit @invigorzz313  [8dff7b0](https://github.com/Niketkumardheeryan/ML-CaPsule/pull/746/commits/8dff7b09d20030c08f389e3c2c9c000bfbc76538)

**Comment by Niketkumardheeryan** [comment]
@AKing-283  add results in readme.md file, also include the steps to use Gradio UI,

**Comment by AKing-283** [comment]
Hello PA @Niketkumardheeryan here is my changes and I have added some changes in readme file too in commit 
https://github.com/Niketkumardheeryan/ML-CaPsule/pull/746/commits/8deb15653d26c229216a093ddcbdf2a08fae7dad and https://github.com/Niketkumardheeryan/ML-CaPsule/pull/746/commits/3ebcbc7c1b8c97962ece9078b8101a534178a486

**Pull request merged**
