### PR TITLE
Indian Currency Notes Classification

### PR DESCRIPTION
**Pull request by aaradhyasinghgaur**
Closes :- #779
Approach I'd taken :- 1.  Utilizing Multiple Network Architectures:

To classify different currency notes such as -
1)Ten Rupee Notes
2)Twenty Rupee Notes
3)Fifty Rupee Notes
4)Hundred Rupee Notes
5)Two Hundred Rupee Notes
6)Five Hundred Rupee Notes, and,
7)Two Thousand Rupee Notes.
        I will employ five distinct deep learning network architectures:

   - DenseNet121
   - Xception
   - VGG16
   - ResNet50
   - InceptionV3

 2. Data Augmentation Techniques:
    To enhance the accuracy and robustness of the models, we will apply various data augmentation techniques such as:

   - Rotation
   - Zooming
   - Flipping (horizontal and vertical)
   - Shearing
   - Brightness adjustments

These techniques will artificially expand the dataset and help prevent overfitting.
3. Model Performance Comparison:
I  will evaluate and compare the performance of each model using the following metrics and visualizations:

   - Accuracy Score: To measure the overall correctness of the models.
   - Loss Graph: To visualize the loss during training and validation phases.
   - Accuracy Graph: To track accuracy improvements over epochs.
   - Confusion Matrix: To provide a detailed breakdown of model performance across different diamond shapes, highlighting precision, recall, and F1 score for each category.

5.    Exploratory Data Analysis (EDA):
    Before training the models, I will perform comprehensive exploratory data analysis (EDA) on the dataset to understand its structure. This will include:

  -  Distribution of images across different diamond shapes.
  -  Image quality and resolution consistency.
  -  Identifying any class imbalances.
   - Visualizing sample images from each category.

 6.   README File:
    A README file will be created to document the entire process according to the READMe template.
    
@Niketkumardheeryan @invigorzz313 kindly review my pr and assign suitable lablel (Level-3) for it if possible cause I have trained the dataset using 5 different models , used data-augmentation techniques to increase the accuracy of models in various conditions , added custom layesr , done EDA analysis which takes a lot of time and computational resources.

In case of no problems kindly merge it to the repo sir . thank you for your time.

### CODE REVIEW

**Comment by kyra-09** [comment]
@Niketkumardheeryan kindly review my pr and in case of no problems kindly merge it with suitable labels.

**Comment by aaradhyasinghgaur** [comment]
@invigorzz313 kindly review my pr and in case of no problems kindly merge it too with suitable label.

**Comment by Niketkumardheeryan** [comment]
@aaradhyasinghgaur you have made same mistake, please add readme.m file in main folder, and delete it from there .

**Comment by aaradhyasinghgaur** [comment]
Okay sir... I'll do it right now.

**Comment by invigorzz313** [comment]
@aaradhyasinghgaur The requirement**s**.txt file should be properly written. You could optionally include versions but the descriptions should be commented.

**Pull request merged**
