### PR TITLE
Added Parkinsons Disease Prediction [Issue #526]

### PR DESCRIPTION
**Pull request by roysammy123**
Added all the source code files for Parkinson's Disease Prediction along with ReadME file against[ Issue #526](https://github.com/Niketkumardheeryan/ML-CaPsule/issues/526) . Please review and merge this PR @Niketkumardheeryan .

Also, please assign level 1/2/3 to the issue so that this can count towards my contribution as part of GSSoC'24. Thank you

### CODE REVIEW

**Comment by invigorzz313** [comment]
LGTM

**Comment by roysammy123** [comment]
Hi @invigorzz313, will be really thankful if you can kindly attach the level 2 label in the issue linked with this PR?

**Comment by Niketkumardheeryan** [comment]
And commit in Capsule 1.1 Branch

**Comment by roysammy123** [comment]
Hi,

Can you please merge this PR for now? I will add the new files in a separate PR in a few days. Would really appreciate

**Pull request closed without merging**
