### PR TITLE
Time Series Forecasting Models using Python

### PR DESCRIPTION
**Pull request by durbar2003**
Updated Readme, proper comments in code

### CODE REVIEW

**Comment by durbar2003** [comment]
@Rutikab12

**Comment by Niketkumardheeryan** [comment]
@durbar2003 we can not accept   .py  file so please replace it with .ipynb file

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
Upload the .ipynb file instead of .py file.

**Comment by durbar2003** [comment]
okay

**Pull request closed without merging**
