### PR TITLE
Centroid digits

### PR DESCRIPTION
**Pull request by mohanadtalat91**
I've created this pr according to issue #398. 
I've add the project's file and README file. 

Feel free to let me edit this pr till it'll be merged.

### CODE REVIEW

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
- Add headings in the .ipynb file
- Add requirement.txt for libraries version
- Make proper readme with bullet points.

**Comment by mohanadtalat91** [comment]
> * Add headings in the .ipynb file
> * Add requirement.txt for libraries version
> * Make proper readme with bullet points.

1.Okay, I'll add headlines in jupyter file.
2.But add section for requirements of libraries that I used in README file 'Tools' section.
3.Okay, I'll improve it.

**Comment by Niketkumardheeryan** [comment]
@mohanadtalat91 last day to commit changes otherwise it will be closed

**Comment by mohanadtalat91** [comment]
> @mohanadtalat91 last day to commit changes otherwise it will be closed

Does it look good  ??

**Pull request closed without merging**
