### PR TITLE
Facerecognition: updated deepface.ipynb

### PR DESCRIPTION
**Pull request by Raghucharan16**
this solves #630 and new version of #645

### CODE REVIEW

**Comment by invigorzz313** [comment]
You need to run all the cells for the proper output. 

image

**Comment by Raghucharan16** [comment]
@invigorzz313 ofcourse I ran it. And attached the output of every cell in the pdf.

**Comment by invigorzz313** [comment]
> @invigorzz313 ofcourse I ran it. And attached the output of every cell in the #645 mentioned pdf. also attaching the same here. [deepface.pdf](https://github.com/Niketkumardheeryan/ML-CaPsule/files/15504517/deepface.pdf)

There seems to be an issue then. The PDF you shared has additional cells but your commits in this PR has missing cells after the one in the above shared screenshot.

**Comment by Raghucharan16** [comment]
@invigorzz313 I've updated the deepface.ipynb file so could please check that once.

**Comment by invigorzz313** [comment]
> @invigorzz313 I've updated the deepface.ipynb file so could please check that once. And anyway I'll update it once again.

Did you push those changes after updating? Because I notice no new changes since last.

**Comment by Raghucharan16** [comment]
@invigorzz313 My bad, may be I didn't push the changes I guess now you can check the file.

**Comment by Niketkumardheeryan** [comment]
@Raghucharan16  use matplotlib or any other libraray to show image used in the project  and proper comments in your code , add results in your readme.md file.

**Comment by Raghucharan16** [comment]
@invigorzz313  notebook and readme has been updated accordingly. check it out once.

**Pull request merged**
