### PR TITLE
Keyframes_Extraction_and_Object_Detection(for that  key  frame)

### PR DESCRIPTION
**Pull request by omkar806**
Description - So this is my project all about the key frames extraction from a particular video and saving it with the timestamp into a folder and then performing the object detection using YOLO V3 Model for each key frame and also givinig the count for the maximum number of objects present in which key frame .

### CODE REVIEW

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
You can remove .ipynb_checkpoints , this is not necessary.

**Comment by Niketkumardheeryan** [comment]
> Description - So this is my project all about the key frames extraction from a particular video and saving it with the timestamp into a folder and then performing the object detection using YOLO V3 Model for each key frame and also givinig the count for the maximum number of objects present in which key frame .

add proper headings in readme.md file and in ur .ipynb file add a demo and don't show output as NumPy array, ur file only consist of array as output ,change it ...

**Comment by omkar806** [comment]
okay I will add headings and also what do you mean by demo  like what exactly should I add in .ipynb file ?

**Comment by omkar806** [comment]
are  the changes done by me in the .ipynb file and the readme.md file correct or I have to work upon it more ?

**Comment by omkar806** [comment]
are the changes done by me in the .ipynb file and the readme.md file correct or I have to work upon it more ? If anything is wrong please I will fix it ? .....

**Review by Rutikab12 — APPROVED** [review]

**Comment by Niketkumardheeryan** [comment]
> are the changes done by me in the .ipynb file and the readme.md file correct or I have to work upon it more ? If anything is wrong please I will fix it ? .....

please add a demo in your readme.md file

**Comment by omkar806** [comment]
I will add the demo today only ....

**Comment by omkar806** [comment]
I have added a demo in the readme.md file please check it out and please let me know if there are any changes that need to be done

**Review by pratishthaa — CHANGES_REQUESTED** [review]
Adding a demo meant more like adding an actual demo video showing how your model is working through an interface.

**Comment by omkar806** [comment]
okay ..

**Comment by omkar806** [comment]
I have made the video but I am not able to commit as I had made a larger video file but now I deleted that larger video file and added a smalller video file but when I commit it still says that previous larger video file cannot be commited even though I have deleted the file from the cloned location

**Comment by omkar806** [comment]
please can anyone guide me I am not able to commit the video because I initially tried to commit a video of more than 100 mb then I deleted that vidoe from the Key-frames-folder on my local machine and added a video less than 100 mb and then I again tried to commit but its still giving me the error for the previous commit  like the new video is not considered .

**Comment by omkar806** [comment]
Please can anyone help my demo video is ready ....but I am not able to commit due to the above issues ...

**Comment by pratishthaa** [comment]
@omkar806 Did u try uploading the video in your repo?

You can do one thing try drag and drop directly into readme.

Still if there are issues, upload onto your drive and provide the link in your readme with the label 'check demo here' or anything else.

**Comment by omkar806** [comment]
Okay

**Pull request closed without merging**
