### PR TITLE
Github Topic Scraper added

### PR DESCRIPTION
**Pull request by aritra1804**
Issue #422 

### Description of the Project:
This is web scraping project According to me it would be really helpful and beneficial for developers who are starting out to get data of different github repositories based on different topics.

### What it does:
- It's going to scrape https://github.com/topics.
-  It'll get a list of topics. For each topic, we'll get the topic title, topic page URL and topic description.

### Approach followed:
1. Scrape the list of topics from the page.
2. Scrape the top repo lists from the chosen topic page.

### CODE REVIEW

**Comment by aritra1804** [comment]
@Niketkumardheeryan @Rutikab12 pls check the pr

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
Add requirement.txt file.

**Comment by Niketkumardheeryan** [comment]
> @Niketkumardheeryan @Rutikab12 pls check the pr

try to show the working of each function (run it)

**Comment by aritra1804** [comment]
@Niketkumardheeryan  @Rutikab12 pls check I have added the requirements.txt. Also, I have run all commands

**Comment by aritra1804** [comment]
@Niketkumardheeryan @Rutikab12 pls check and merge. It's been 1 week

**Pull request merged**
