### PR TITLE
Movie recommender system

### PR DESCRIPTION
**Pull request by Binal02Singh**
Created A Movie Recommendation System Using Python for issue no. #221

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
@Binal02Singh Hey your ,ipynb file don't have any comment or proper headings, Make sure that your code has proper comments ...

**Comment by Binal02Singh** [comment]
@Niketkumardheeryan okay I will update it.

**Comment by Binal02Singh** [comment]
I have updated the file with proper comments

**Review by hritikksingh — CHANGES_REQUESTED** [review]
You have made the readme.md in a wrong way.
I would suggest try not to use word 'I' and instead change it to 'we'.
The readme should be considered as a generalized text.
Others thoughts?
@Niketkumardheeryan @Rutikab12 @pratishthaa

**Comment by pratishthaa** [comment]
Tip for your readme: always add what the project is, how helpful it is and a proper description of data used.

**Comment by Binal02Singh** [comment]
Thank you @hritikksingh and @pratishthaa I will remember your points and update the readme file

**Comment by Binal02Singh** [comment]
@pratishthaa @hritikksingh @Niketkumardheeryan I have updated the readme file pls check and let me know if you require any other change.

**Pull request merged**
