### PR TITLE
Added Multimodal visual qna using two advanced models-BLIP & CLIP

### PR DESCRIPTION
**Pull request by Panchadip-128**
his repository contains an implementation of a Visual Question Answering (VQA) model built using the BLIP (Bootstrapping Language-Image Pre-training) framework. This model can understand image content and answer questions related to the provided images. A tool that reads an image based on ML algorithms( BLIP model) and implements Visual QA which answers questions based on user prompts for the image, deployed through Gradio web application

Overview
This project focuses on developing Visual Question Answering (VQA) systems using two models: CLIP (Contrastive Language-Image Pretraining) and BLIP (Bootstrapped Language-Image Pretraining). The goal of VQA is to answer questions about an image by jointly learning from both textual and visual information. This project demonstrates how to utilize the CLIP and BLIP models for VQA tasks, and it includes the training, validation, and testing procedures, as well as metrics for evaluation.

Data Overview:
The dataset used for this project is sourced from the VizWiz 2023 VQA challenge. It contains three main components:

train.json: The training set with image URLs, questions, and answers. val.json: The validation set. test.json: The test set without answer labels for evaluation purposes. Each entry in the dataset includes:

Image: The visual input for the model. Question: The textual question that the model needs to answer. Answers: A list of possible answers (for training/validation) and their confidences. The dataset is preprocessed to create a balanced set by stratifying based on the answerable and answer_type labels.

CLIP-Based VQA Model
Overview:
The CLIP-based VQA model uses the pre-trained CLIP model to extract both visual and textual embeddings. The two embeddings are concatenated to form a single vector, which is then passed through a fully connected network to predict the answer.
qna3
qna2
qna-1

### CODE REVIEW

**Comment by Panchadip-128** [comment]
@Niketkumardheeryan Please review as time is less

**Comment by Niketkumardheeryan** [comment]
@Panchadip-128 expecting more modular code with proper comments

**Comment by Panchadip-128** [comment]
Sir, but output and results are properly coded seperatelty for both the model notebooks, please tell me next steps for this

**Comment by Panchadip-128** [comment]
@Niketkumardheeryan Sir should i add comments and then re-upload? Please tell

**Comment by Panchadip-128** [comment]
@Niketkumardheeryan Sir, i understood the problem that code in the BLIP File is not modular but quality of output, deployment through Gradio and all other aspects are great, code is modular in other files as well. Please dont reject because of the one file

**Comment by Panchadip-128** [comment]
@Niketkumardheeryan Done sir that one file also i made the code into modules

**Pull request closed without merging**
