### PR TITLE
Readme updated

### PR DESCRIPTION
**Pull request by arunitasahu**
**Improved the following points -**
Sorted the projects according to difficulty.
All contributors images are visible at last alphabetically.

solves issue #625 .

### CODE REVIEW

**Comment by invigorzz313** [comment]
Please tag the corresponding issue number.

**Comment by arunitasahu** [comment]
> Please tag the corresponding issue number.

solves issue #625 .

**Comment by arunitasahu** [comment]
@invigorzz313 please have a look.

**Comment by Niketkumardheeryan** [comment]
@arunitasahu  plesae try to improve more , you can create a new totally new readme.md  file  , no need to imrove as there is many mistakes in current readme.md file, 

But these changes we cant merge improve it more .

**Comment by arunitasahu** [comment]
sure

**Pull request merged**
