### PR TITLE
Facerecognition

### PR DESCRIPTION
**Pull request by Raghucharan16**
solves #630 added face detection, face recognition and facial attribute analysis with different models under one hood.

### CODE REVIEW

**Comment by invigorzz313** [comment]
You can submit only when you have a corresponding assigned issue.
If you have already created one and has it assigned, kindly tag it here.

Also, please add a ReadMe.md file and ensure there is .ipynb files and not .py ones.

**Comment by Raghucharan16** [comment]
@invigorzz313 Updated the PR review it. Thanks

**Comment by invigorzz313** [comment]
@Raghucharan16 Please add a ReadMe.md file

**Comment by Raghucharan16** [comment]
@invigorzz313 Updated the readme

**Comment by Raghucharan16** [comment]
I don't know what the problem is occuring to you. I've retested it and modified it. so please check once. thank you. everything is working fine. Here is the executed code.
[deepface.pdf](https://github.com/Niketkumardheeryan/ML-CaPsule/files/15479270/deepface.pdf)

**Pull request closed without merging**
