### PR TITLE
Updated README.md

### LINKED ISSUE #699: Readme.md update required
small update in readme.md required, I can add some animated emojis in the file , That will look good .
@Niketkumardheeryan assign this issue to me I will update the readme file 
I am working under gssoc

### PR DESCRIPTION
**Pull request by Meetjain1**
closes #699 
updated readme.md file

### CODE REVIEW

**Comment by Meetjain1** [comment]
@Niketkumardheeryan have a look on this pr . Thanks

**Comment by Meetjain1** [comment]
@Niketkumardheeryan have a look on this pr

**Comment by Meetjain1** [comment]
@Niketkumardheeryan have a look on this pr

**Comment by Meetjain1** [comment]
@Niketkumardheeryan can you please merge this pr Pending from more than 40 days . Thanks

**Comment by Meetjain1** [comment]
@Niketkumardheeryan ????

**Comment by Meetjain1** [comment]
> @Niketkumardheeryan @invigorzz313 have a look on this pr pending since june 3rd

@Niketkumardheeryan

**Comment by Meetjain1** [comment]
> @Niketkumardheeryan @invigorzz313 have a look on this pr pending since june 3rd

please review this pr . Thanks

**Comment by Meetjain1** [comment]
> > @Niketkumardheeryan @invigorzz313 have a look on this pr pending since june 3rd
> 
> please review this pr . Thanks

@Niketkumardheeryan @invigorzz313

**Comment by Niketkumardheeryan** [comment]
@Meetjain1 we are already working on our readme.md file and your changes are minors ,can't with these changes only

**Pull request closed without merging**
