### PR TITLE
PR no - #772 --> Face Mask Detection using Machine learning(DL)

### PR DESCRIPTION
**Pull request by KamakshiOjha**
I have added the files, can you please review the work.

### CODE REVIEW

**Comment by KamakshiOjha** [comment]
I have added the files, can you please review the work, previously i have done Face mask detection and now Drowsiness Dtetction using EEG signals

**Comment by KamakshiOjha** [comment]
I have added the files, can you please review the work, previously i have done Face mask detection and now Drowsiness Dtetction using EEG signals

**Comment by KamakshiOjha** [comment]
I have added the files, can you please review the work, previously i have done Face mask detection and now Drowsiness Detection using EEG signals.

**Comment by KamakshiOjha** [comment]
I have added the files, can you please review the work, previously i have done Face mask detection and now Drowsiness Detection using EEG signals.

**Comment by Niketkumardheeryan** [comment]
> I have added the files, can you please review the work, previously i have done Face mask detection and now Drowsiness Detection using EEG signals.

Great work @KamakshiOjha ,just add results in your readme.md file , and use more cells in your code for better readability.

2. There is an output which printing 2 only , if needed you can only print few 2s as per requirements

**Comment by KamakshiOjha** [comment]
I have added the images, since this is a heavy code its hard to run again.

**Comment by KamakshiOjha** [comment]
Can you review the work, I have added the result into the Readme file.

**Comment by invigorzz313** [comment]
image

You seem to have included 2 projects in a single PR. For different issues, there must be different PRs, so that level labels are properly assigned.

**Comment by KamakshiOjha** [comment]
I tried to open 2 PRs but it always direct me to the previous pr... i will try to create separate one

**Comment by KamakshiOjha** [comment]
Can you please merge this one, so I can add for next

**Comment by KamakshiOjha** [comment]
I want to add drowsiness detection and sarcasm detection folder, I request u please accept this pull request, so I can contribute further.

**Comment by Niketkumardheeryan** [comment]
@KamakshiOjha we can't you pr until you use more for code execution in your .ipynb file, we follow some guidelines for For code quality, Please make required change create a New PR .

**Comment by KamakshiOjha** [comment]
U need spacing between code? Or u need more algorithm?

**Pull request closed without merging**
