### PR TITLE
Loan Prediction Project

### PR DESCRIPTION
**Pull request by sanskritiagr**
I have added the project- Loan Prediction.

### CODE REVIEW

**Comment by sanskritiagr** [comment]
Please assign a level too for GsSoc'24. It is with regard to the issue I was assigned.

**Comment by sanskritiagr** [comment]
@Niketkumardheeryan please look into it.

**Comment by Niketkumardheeryan** [comment]
hi @sanskritiagr  good work, jsut need to improve readme.md file, attach ss of after running your flask app ,And add more comments in your .ipynb file  for readability.

**Comment by sanskritiagr** [comment]
Done

**Comment by sanskritiagr** [comment]
Please merge it.

**Comment by vishalmaurya850** [comment]
> I have added the project- Loan Prediction. 

Please assign me this Project I have a good experience in Data Science and Machine Learning.

**Comment by sanskritiagr** [comment]
Is there any problem merging this? @Niketkumardheeryan

**Comment by sanskritiagr** [comment]
Please merge this. It has been a long time now.

**Comment by vishalmaurya850** [comment]
> hi @sanskritiagr  good work, jsut need to improve readme.md file, attach ss of after running your flask app ,And add more comments in your .ipynb file  for readability.
> 
> 

Please assign me this Project as I have a good experience in working with projects in Data Science.

**Comment by sanskritiagr** [comment]
@Niketkumardheeryan I did the changes you wanted me to do. Please merge this file.

**Pull request merged**
