### PR TITLE
Spam Mail Detection

### PR DESCRIPTION
**Pull request by SoumyoNathTripathy**
#248

### CODE REVIEW

**Comment by SoumyoNathTripathy** [comment]
please merge it.

**Comment by Niketkumardheeryan** [comment]
@SoumyoNathTripathy make your readme.md file better, You cat refer to Youtube, and remove ipl wala part and your spam classification as well...

**Comment by SoumyoNathTripathy** [comment]
@Niketkumardheeryan i need to make the readme file better?

**Comment by Niketkumardheeryan** [comment]
> @Niketkumardheeryan i need to make the readme file better?

yes

**Pull request closed without merging**
