### PR TITLE
Added Face emotion classification Training model

### LINKED ISSUE #1143: Face Expression detection through vedio and camera
# Facial Expression Detection through Video and Camera 🎥😄
This project utilizes supervised learning to detect and classify facial expressions in real-time using video and camera input. It leverages the FER (Facial Expression Recognition) dataset to train a model capable of recognizing various emotions such as happiness, sadness, surprise, anger, and more.

## Features
Real-time facial expression detection using live camera feed 📸
Supports multiple expressions including happiness, sadness, anger, surprise, etc. 😊😢😡😲
Uses a trained supervised learning model for accurate prediction
Integration of OpenCV for video capture and face detection
Easy-to-use interface for emotion tracking during live video input
## Dataset
FER Dataset: A widely-used dataset for emotion detection, containing labeled facial images with corresponding emotion categories.
## Tech Stack
Python 🐍
OpenCV for real-time video processing 🎥
Supervised Learning models (e.g., Logistic Regression, SVM, etc.)
TensorFlow/Keras or Scikit-learn for model training 🤖

### PR DESCRIPTION
**Pull request by shivenyadavs**
closes #1143 
Emotion Classification Model
This project provides an emotion classification model that can be used to detect facial emotions in real-time using either pre-recorded video files or live webcam input. The repository includes:

train.py: Script to train the emotion classification model.
test.py: Script to test the model using either a video file or live webcam feed. Users can modify the video file path in the script for testing or switch to live webcam detection.
Features:
Real-time emotion detection via webcam.
Easy-to-modify test video path for custom testing.
Efficient model training using a standard dataset (not included in this repo).
How to Use:
Training: Use train.py to train your model. Ensure you have the appropriate dataset loaded for training.
Testing: In test.py, you can either:
Provide a path to a video file for emotion detection, or
Use the webcam for real-time detection by setting the webcam option.

### CODE REVIEW

**Comment by shivenyadavs** [comment]
@Niketkumardheeryan can you please check the changes

**Comment by Niketkumardheeryan** [comment]
@shivenyadavs hey we don't accept.py files , please try to add .ipynb file , and readme.md and requirment.txt file

**Comment by shivenyadavs** [comment]
@Niketkumardheeryan i have executed each and every cell in the ipynb file please check it sir.

**Comment by shivenyadavs** [comment]
@Niketkumardheeryan can you please merge this pr i have changed it as you mentioned

**Comment by Niketkumardheeryan** [comment]
@shivenyadavs  there is no readme file and your code have errors and well documented, Please maintain the proper headings in your code , 

Is this a copied code??

**Comment by shivenyadavs** [comment]
it is in the folders
i cant upload files with 4gb as it contains photos for training there are 35000 images

**Pull request merged**
