### PR TITLE
CS:GO Round Winner Classification

### PR DESCRIPTION
**Pull request by tandrimasingha**
Title: CS: GO Round Winner Classification
Aim: Predict who wins individual snapshots of rounds. Using 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitting algorithm for the model by checking the accuracy scores.
I am a GSSoC22 participant 
@Niketkumardheeryan Please merge it.

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
@tandrimasingha add proper comment in your code.......

**Review by pratishthaa — CHANGES_REQUESTED** [review]
You have used 3 classifiers, but there are others too, you can use the XGBoost classifier too. It usually yields more than LR.(or any other classifier you want to add)

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
use other classifier to get more accuracy.

**Comment by hritikksingh** [comment]
I can't see the issue Linked with the PR

**Pull request closed without merging**
