### PR TITLE
Feature Request: News Articles Category Prediction

### PR DESCRIPTION
**Pull request by ReaganBlade**
# **Pull Request Title**:  **News Articles Category Prediction**

## Issue No :  #1102

---

## **Description**:
This pull request implements the following changes:
1. Added a **Support Vector Classifier (SVC)** model to the Streamlit app for classifying news articles into categories.
2. Integrated **GridSearchCV** to optimize hyperparameters for the SVC model, improving classification accuracy.
3. Updated the Streamlit interface to allow users to input text and classify it using the best-performing model (SVC).
4. Modified **requirements.txt** to include necessary dependencies such as `scikit-learn`, `streamlit`, and other relevant libraries.
5. Enhanced the README.md file with a detailed project description, setup instructions, and usage notes.

---

## **Changes Made**:
- **`model.py`**: Created a new file for building and exporting the SVC model with the optimized hyperparameters.
- **`app.py`**: Integrated the SVC model into the Streamlit app, allowing the user to classify news articles.
- **`requirements.txt`**: Added required libraries such as `scikit-learn`, `joblib`, and others.
- **`README.md`**: Updated the README file with more comprehensive instructions, including the description of the Jupyter Notebook used for model building.

---

## **Testing**:
- Tested the Streamlit app locally to ensure that the SVC model correctly classifies articles based on input.
- Verified that the app responds as expected with various inputs and handles edge cases.
- Ran cross-validation on the SVC model, confirming that the accuracy has improved compared to the baseline model.

### CODE REVIEW

**Comment by ReaganBlade** [comment]
Please go through the Pull Request and Merge the Branch.

**Comment by ReaganBlade** [comment]
@Niketkumardheeryan Sir please add Hacktoberfest-accepted, gssoc-ext Labels to this pull request

**Comment by Niketkumardheeryan** [comment]
Hey @ReaganBlade  we don't accept.py file try to add .ipynb file

**Comment by Niketkumardheeryan** [comment]
Create new PR now

**Pull request closed without merging**
