### PR TITLE
added pytorch tabular short tutorial, refer to issue #302

### PR DESCRIPTION
**Pull request by WhiteWolf47**

### CODE REVIEW

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
Refer to other PR and files in their PR's, for idea to include which files in a PR.

**Comment by WhiteWolf47** [comment]
@Rutikab12 sorry, i did not understand what you are trying to say, can you please elaborate?

**Comment by Rutikab12** [comment]
> @Rutikab12 sorry, I did not understand what you are trying to say, can you please elaborate?

Please refer to other open pull requests to understand how to make good PR.

**Comment by WhiteWolf47** [comment]
okay will do

**Comment by Niketkumardheeryan** [comment]
> @Rutikab12 sorry, i did not understand what you are trying to say, can you please elaborate?

add .readme.md file  like other repos have  ,

**Comment by WhiteWolf47** [comment]
@Rutikab12 added readme file, please review.

**Comment by WhiteWolf47** [comment]
@Rutikab12  added readme , pls review.

**Pull request merged**
