### PR TITLE
Created Brain Tumor Detection.

### PR DESCRIPTION
**Pull request by TheNaiveSamosa**
Created a new sub project named Brain Tumor Detection. Added README and a ipynb.

### CODE REVIEW

**Comment by TheNaiveSamosa** [comment]
Check the issue #556 and do merge this. Add labels to the issue and PR. GSSoC 2024, Level 3. And do merge this PR.

**Comment by invigorzz313** [comment]
LGTM

**Comment by TheNaiveSamosa** [comment]
so can you merge it?

**Comment by TheNaiveSamosa** [comment]
If it Looks good then could you please merge the PR. I've commented in the
PR and in the Issue too. you've reviewed the code and still not merged the
PR. Please look into the matter.

**Comment by TheNaiveSamosa** [comment]
Anyone here? Please do reply!! Is this an active Repository? Please do merge my PR.

**Comment by invigorzz313** [comment]
@TheNaiveSamosa There are no conflicts now but from next time, do create a new branch in your local repo before making a PR. Avoid committing from master branch.

**Pull request merged**
