### PR TITLE
Feed-forward neural networks (Deep Learning Algorithm)

### PR DESCRIPTION
**Pull request by ranamanish674zu**
@Niketkumardheeryan i complete issue #826 
techniques- Feed-forward neural networks and deep learning 
here are some screenshot ->
image
image
image
@Niketkumardheeryan could you please review the request

### CODE REVIEW

**Comment by ranamanish674zu** [comment]
@Niketkumardheeryan sir could you please chake

**Comment by Niketkumardheeryan** [comment]
Hi @ranamanish674zu Good work, just use accuracy charts in your code and and add Readme.md file

**Comment by ranamanish674zu** [comment]
> Hi @ranamanish674zu Good work, just use accuracy charts in your code and and add Readme.md file

Okay  @Niketkumardheeryan

**Comment by ranamanish674zu** [comment]
> Hi @ranamanish674zu Good work, just use accuracy charts in your code and and add Readme.md file

@Niketkumardheeryan  could you please add the label to issue , you assign but not label it with 1,2 or 3 ?

**Comment by ranamanish674zu** [comment]
@Niketkumardheeryan sir i have added the readme file and also added a accuracy chart to see the accuracy using matplotlib.
fixes issue #826  @Niketkumardheeryan could you please review now

**Comment by invigorzz313** [comment]
@ranamanish674zu The requirements.txt file is not correctly written. Refer any tutorials for the same. You would just serially name the libraries and optionally the versions too.

**Comment by ranamanish674zu** [comment]
@invigorzz313 , @Niketkumardheeryan i have modified the requirement.txt as you said , can you review it

**Pull request merged**
