### PR TITLE
Create a new Improved Readme.md file for ML capsule #989

### PR DESCRIPTION
**Pull request by sreevidya-16**
I updated readme file in a creative way
@Niketkumardheeryan , view this PR and let me know, if any modifications are required

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
@sreevidya-16 remove Project , Available project Headline is enough for that and remove Six sigma as well.

**Comment by Niketkumardheeryan** [comment]
Try to use chat GPT if that can be reproduce it better.

**Comment by Niketkumardheeryan** [comment]
@sreevidya-16 ?

**Comment by sreevidya-16** [comment]
@Niketkumardheeryan, I have updated, please have a look on this PR

**Comment by sreevidya-16** [comment]
@Niketkumardheeryan, I have updated, please have a look on this PR

**Pull request merged**
