### PR TITLE
Document scanner 

### PR DESCRIPTION
**Pull request by arunitasahu**
closes : #766 
The document scanning process involves several key steps:
1. **Image Loading**: Load the input image containing the documents to be scanned.
2. **Preprocessing**: Preprocess the image by converting it to grayscale, applying Gaussian blur to reduce noise, and performing edge detection to detect document contours.
3. **Contour Detection**: Identify contours in the edge-detected image to locate the boundaries of the document(s).
4. **Perspective Transformation**: Apply perspective transformation to obtain a top-down view of the document(s) by correcting for perspective distortion.
5. **Displaying the Result**: Display the original image and the scanned documents side by side for visual comparison.

### CODE REVIEW

**Comment by arunitasahu** [comment]
@invigorzz313 @Niketkumardheeryan
Please review my pr and in case of no problems merge it with suitable label please.

**Comment by invigorzz313** [comment]
@arunitasahu The description you wrote in the ReadMe.md file, its better if you include it in the .ipynb itself. Then the notebook would be interactive with proper code and text cells. Because we expect the code to be properly commented with explanations. 
As for the ReadMe.md, you can describe the techstack used, libraries used and aim & objective. Also include sample examples in it (original and final image pairs).

**Comment by arunitasahu** [comment]
@invigorzz313 I have made the required changes .Please have a look into it.

**Comment by Niketkumardheeryan** [comment]
@arunitasahu No cell Executed in your .ipynb file, please make it better readable with more commenting , also show used images in code  ,

**Comment by arunitasahu** [comment]
- I've improved the readability of the .ipynb file by adding more comments throughout the code. 
- The code cells will be executed in your Jupyter notebook when you insert the images into the specified path.The results will then be displayed on your local machine.
- Additionally, I have included instructions on how to run the program. 

To illustrate how the code works and what the output looks like, I have added sample images. These images show both the functioning of the code and the appearance of the output.

Screenshot 2024-06-21 020435
Screenshot 2024-06-21 020510


@Niketkumardheeryan @invigorzz313

**Comment by invigorzz313** [comment]
@arunitasahu It is suggested that you display the input and output images in the code too. For this you can use matplotlib library to display the figures. That way, the images are always visible instead of using cv2.waitkey for temporary viewing.
And put in more comments example the "preprocessing and finding document contours" part, you can explain the major important commands being used.

**Comment by arunitasahu** [comment]
@invigorzz313 @Niketkumardheeryan  I've made the necessary changes to integrate matplotlib for displaying input and output images directly . Additionally, I've added detailed comments to explain the major commands used in the preprocessing and contour detection stages. 
Here is a sample of output - 
Screenshot 2024-07-06 044455

**Pull request merged**
