### PR TITLE
I made a project on Sudoku Solver using CNN.

### PR DESCRIPTION
**Pull request by pratyush2303**
I made this project against the issue of "Add a new project which will give a basic understanding of CNNs (Deep Learning) that is a Sudoku Solver".

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
@pratyush2303 is it a udacity project..

**Comment by pratyush2303** [comment]
No, it is not a udacity given project. This is my own made capstone project. This was made for basic understanding of neural networks for beginners.

**Comment by Niketkumardheeryan** [comment]
> @Niketkumardheeryan No, it is not a udacity given project. This is my own made capstone project. This was made for basic understanding of neural networks for beginners.

ok

**Comment by Niketkumardheeryan** [comment]
> > @Niketkumardheeryan No, it is not a udacity given project. This is my own made capstone project. This was made for basic understanding of neural networks for beginners.
> 
> ok

and mention your issue ...

**Comment by pratyush2303** [comment]
Issue name - "Add a new project which will give a basic understanding of CNNs (Deep Learning) that is a Sudoku Solver".
Issue link - "https://github.com/Niketkumardheeryan/ML-CaPsule/issues/251"
Issue no- 251

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
please remove the repository readme file from your PR.

**Comment by Niketkumardheeryan** [comment]
@pratyush2303 your readme.md file has some issue replace it ....

**Comment by pratyush2303** [comment]
Can I start a new pull request with the changes requested and close this one? @Niketkumardheeryan

**Comment by Rutikab12** [comment]
> Can I start a new pull request with the changes requested and close this one? But I have commit the changes. Please have a look @Niketkumardheeryan

no need to close this one. Just make changes in the forked repo and it will get reflected here

**Comment by pratyush2303** [comment]
@Niketkumardheeryan  @Rutikab12  I have already made changes in forked repo but still it is showing "conflicting files". What should I do?

**Comment by Rutikab12** [comment]
> @Niketkumardheeryan @Rutikab12 I have already made changes in forked repo but still it is showing "conflicting files". What should I do?

had you fetched the upstream?. You can refer [this](https://www.simplilearn.com/tutorials/git-tutorial/merge-conflicts-in-git)

**Pull request closed without merging**
