### PR TITLE
A Cognitive behavioral therapy (CBT) Chatbot using CNN and Tkinter for GUI

### PR DESCRIPTION
**Pull request by paritoshtripathi935**
Adding a new folder that contains Cognitive behavioural therapy (CBT) a chatbot has its purpose is to make mental health support more easily accesbile.
It has some preprocessing for input chats and a basic 3 layered CNN model with the epoch of 200, and I am using python library Tkinter for Gui. 
I am attaching the working image, Ipynb file, a readme file for more information. 
I am GSSOC 2022 participant.

### CODE REVIEW

**Comment by paritoshtripathi935** [comment]
@Rutikab12 please assign this pr Gssoc Tag if possible

**Comment by Rutikab12** [comment]
Hey @paritoshtripathi935 we have merged your PR.

**Comment by paritoshtripathi935** [comment]
> Hey @paritoshtripathi935 we have merged your PR.

But if there is no Gssoc tag it will not count towards contribution to Gssoc

**Comment by Rutikab12** [comment]
Don't worry it will be counted.

**Pull request merged**
