### PR TITLE
Heart Disease Classifier Using ECG Scan

### PR DESCRIPTION
**Pull request by srajan-kiyotaka**
Deep Learning CNN Model To Predict Heart Disease Using ECG Scan.
In This Model, The Model is Trained Using The ECG Image Dataset.
The model accuracy is 100%.
I had also added the readme file as well as the dataset and images used.
I had made two .ipynb files:-
- first is for understanding purpose.
- the second is more efficient. 
### Issue No. : #274

### CODE REVIEW

**Review by Rutikab12 — APPROVED** [review]

**Comment by Rutikab12** [comment]
> Deep Learning CNN Model To Predict Heart Disease Using ECG Scan. In This Model, The Model is Trained Using The ECG Image Dataset. The model accuracy is 100%. I had also added the readme file as well as the dataset and images used. I had made two .ipynb files:-
> 
> * first is for understanding purpose.
> * the second is more efficient.

Add Issue number

**Comment by Niketkumardheeryan** [comment]
> Deep Learning CNN Model To Predict Heart Disease Using ECG Scan. In This Model, The Model is Trained Using The ECG Image Dataset. The model accuracy is 100%. I had also added the readme file as well as the dataset and images used. I had made two .ipynb files:-
> 
> * first is for understanding purpose.
> * the second is more efficient.

Hey if it is 100% you can write research on it... otherwise, your model is  overfitted

**Comment by srajan-kiyotaka** [comment]
@Rutikab12 
Issue No. : #274

**Comment by srajan-kiyotaka** [comment]
@Niketkumardheeryan 
Both the Training Accuracy as well as the Testing Accuracy is 100%,
so I don't think the model is overfit
and for the research paper, I will look into it.

**Comment by Rutikab12** [comment]
> @Rutikab12 Issue No. : #274

Don't comment separately. Mention it in your PR Description.

**Comment by srajan-kiyotaka** [comment]
@Rutikab12 
Now Check.

**Comment by srajan-kiyotaka** [comment]
@Rutikab12 
Hey
I just want to confirm that 
in the leader board, only one PR is mentioned,
and this PR is not mentioned.
Can you just check?

**Comment by Rutikab12** [comment]
@srajan-kiyotaka okay we we'll into that.
@Niketkumardheeryan

**Comment by srajan-kiyotaka** [comment]
@Niketkumardheeryan 
Can you confirm,
It is still not showing on the website.

**Comment by srajan-kiyotaka** [comment]
@Rutikab12 
Any Update?

**Comment by srajan-kiyotaka** [comment]
@Niketkumardheeryan 
Any Update?

**Pull request merged**
