### PR TITLE
Added Coupon Purchase Prediction

### PR DESCRIPTION
**Pull request by Sulagna-Dutta-Roy**
Fixes: #452 

I added all the files and datasets and made separate folder for this.
Environment: Google Colaboratory
Dataset: Kaggle

### CODE REVIEW

**Comment by Sulagna-Dutta-Roy** [comment]
Ok

**Comment by Sulagna-Dutta-Roy** [comment]
Please check I made all the changes. @Rutikab12

**Comment by Niketkumardheeryan** [comment]
> Please check I made all the changes. @Rutikab12
 
print(dictionary_coupons)  print only few rows

and define ur files in reame.md file

**Comment by Sulagna-Dutta-Roy** [comment]
All the dataset rows are depends on datesets. So updated datasets has few rows I've checked there. Also some of the rows are out because of larger.

**Comment by Niketkumardheeryan** [comment]
> All the dataset rows are depends on datesets. So updated datasets has few rows I've checked there. Also some of the rows are out because of larger.

just print 2 to 3 rows only...

**Comment by Sulagna-Dutta-Roy** [comment]
All the big rows just filtered out.

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly check it I added all the changes.

**Comment by Niketkumardheeryan** [comment]
> Kindly check it I added all the changes.

made the required changes ....

**Pull request closed without merging**
