### PR TITLE
Statistical modeling in python 

### PR DESCRIPTION
**Pull request by Nidhi20-7**
#552 Performed statistical modeling on retail dataset using python.

### CODE REVIEW

**Comment by Nidhi20-7** [comment]
Updated readme.md file,please verify it.

**Comment by Niketkumardheeryan** [comment]
hey @Nidhi20-7 , most projects contains these all functions or visualization methods , so please try to add more unique function or package,
Ex. you can use AutoMl library or any other library like this , for better modeling.

**Comment by Niketkumardheeryan** [comment]
@Nidhi20-7 any update on this ....otherwise will close it soon.

**Comment by Niketkumardheeryan** [comment]
Please make another PR ,when you are available

**Pull request closed without merging**
