### PR TITLE
Consumer Complaint Dataset: Leveraging an NLP Pipeline to Analyze Financial Consumer Complaints 

### PR DESCRIPTION
**Pull request by ananas304**
**Description**  
This PR addresses the issue by creating a structured folder for the **Consumer Complaint Dataset** project. It includes:
- The dataset file `complaints_processed.csv`
- A Jupyter Notebook (`Consumer_Complaint_Analysis.ipynb`) demonstrating the NLP pipeline, data preprocessing, and classification
- A `README.md` file with project documentation detailing the purpose, dataset overview, consolidated categories, usage instructions, and potential applications.

**Comment**  
This PR resolves the issue by organizing the dataset and relevant files for better project clarity, facilitating ease of use for future contributors.  

Issue #1125 
Thank you! 😊

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
@ananas304 hey ,you have to execute each cells too, and make sure data used must be preprocessed first , and attach results in readme.md file

**Comment by ananas304** [comment]
I'll work on it. Thanks for pointing it out.

**Comment by ananas304** [comment]
I have made the changes please review it.

**Comment by Niketkumardheeryan** [comment]
You have to attach results,like accuracy and all

**Comment by ananas304** [comment]
I have. It's in the readme page

**Pull request merged**
