### PR TITLE
Add AI Virtual Drag and Drop project using OpenCV

### PR DESCRIPTION
**Pull request by ashis2004**
issue #844 resolved
Description: 
 Captures video frames, detects hand positions, and moves a specified image around the frame based on the distance between the user's index finger and thumb. When the user brings their index finger and thumb close together (less than 20 pixels apart), they can move the image by pointing at a new location.
Implementation processes-
i. imported necessary library
ii. Video Capture and Hand Detector Initialization
iii. Load and Resize Image
iv. Initial Position of the Image
v. Capture Frame and Image Dimensions
vi. Flip frame
vii, Hand Detection
viii, Check if Hands are detected
ix. Find distance between fingers
x.Move if distance is less Than 20
xi. Overlay image on frame'
xii. Display frame.
drag

drop

### CODE REVIEW

**Comment by ashis2004** [comment]
@Niketkumardheeryan please check it

**Comment by invigorzz313** [comment]
@ashis2004 Please tag the corresponding issue. The issue must be assigned to you before you submit the PR.
And the .py file should instead be in .ipynb format, with multiple cells and proper commenting.
Also, include a ReadMe.md file describing the project and the techstack used.

**Comment by ashis2004** [comment]
issues #863 resolved please check it @invigorzz313

**Comment by invigorzz313** [comment]
@ashis2004 You tagged the same PR again, not its issue.
Also .py file should be .ipynb instead and add Readme.md file

**Comment by Niketkumardheeryan** [comment]
@ashis2004 any update?

**Comment by ashis2004** [comment]
i'm Trying

**Comment by Niketkumardheeryan** [comment]
@ashis2004 ??

**Comment by ashis2004** [comment]
> @ashis2004 ??

pls close the issue i'm unable to do

**Pull request merged**
