### PR TITLE
Amazon Alexa Reviews Analysis #252

### PR DESCRIPTION
**Pull request by slothtae**
Added 2 files inside ML-CaPsule/Basic of ML and DL/ML/NLP :
 -> amazon_alexa_sentiment_analysis.ipynb
 -> amazon_alexa.tsv

### CODE REVIEW

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
@Niketkumardheeryan Please see this. (the folder structure)
Add proper readme file for the model.

**Comment by Niketkumardheeryan** [comment]
hey @slothtae, you can add a folder separately in main branch and readme.md file and add proper comments in your file

**Review by Niketkumardheeryan — CHANGES_REQUESTED** [review]
Change the folder

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
Yes, add a separate folder for the project.

**Comment by pratishthaa** [comment]
Yes, apart from the readme, make sure your code has proper comments so that even a beginner can easily understand.

**Comment by hritikksingh** [comment]
Which issue is attached with this PR?

**Review by hritikksingh — COMMENTED** [review]
@Niketkumardheeryan is it allowed to use the NLTK directly and classifying based on direct functions?

**Comment by Niketkumardheeryan** [comment]
> @Niketkumardheeryan is it allowed to use the NLTK directly and classifying based on direct functions?

yes

**Pull request closed without merging**
