### PR TITLE
Add Speed test

### PR DESCRIPTION
**Pull request by mohanadtalat91**
**Issue number** :  #362 

Upload a simple script to show some information about All server around my connected network, It can also determine best server.

It has some function such as { Download Speed, Upload Speed, Ping }.

### CODE REVIEW

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
@mohanadtalat91 Add a proper readme file. Mention Issue number while making PR.

**Comment by mohanadtalat91** [comment]
> @mohanadtalat91 Add a proper readme file. Mention Issue number while making PR.

Issue number : #362

**Comment by Niketkumardheeryan** [comment]
> > @mohanadtalat91 Add a proper readme file. Mention Issue number while making PR.
> 
> Issue number : #362

Don't change main Readme.md file add your own readme.md file in your PR

**Comment by mohanadtalat91** [comment]
> > > @mohanadtalat91 Add a proper readme file. Mention Issue number while making PR.
> > 
> > 
> > Issue number : #362
> 
> Don't change main Readme.md file add your own readme.md file in your PR

Alright, I'll add README file as much as possible.

**Comment by mohanadtalat91** [comment]
> > > @mohanadtalat91 Add a proper readme file. Mention Issue number while making PR.
> > 
> > 
> > Issue number : #362
> 
> Don't change main Readme.md file add your own readme.md file in your PR

Could you plz take a look about my lastest changes ?? @Niketkumardheeryan @Rutikab12 
I've add README for my new project. 
And also edit the main repo's README to mention my directory for my added project.

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
From here also remove the README file of the project from your commit.

**Comment by mohanadtalat91** [comment]
@Niketkumardheeryan
@Rutikab12 
Is it okay or I missed something ?

**Pull request closed without merging**
