### PR TITLE
Clustering Algorithms Documentation added

### PR DESCRIPTION
**Pull request by shreya024**
Related Issue:#466

### CODE REVIEW

**Comment by shreya024** [comment]
@Niketkumardheeryan @Rutikab12 Kindly review

**Review by Rutikab12 — CHANGES_REQUESTED** [review]
Styling for fonts in the file is not perfect. Please re-check.

**Comment by shreya024** [comment]
> Styling for fonts in the file is not perfect. Please re-check.

I have renamed and the styling seems fine now.Kindly review.

**Review by Rutikab12 — APPROVED** [review]

**Comment by shreya024** [comment]
> > > Styling for fonts in the file is not perfect. Please re-check.
> > 
> > 
> > @Rutikab12 I have renamed and the styling seems fine now.Kindly review.
> 
> it will be better if you could add images or sample code with doc

Okay I have added sample code but images I couldn't find so I have given plots to show in the code

**Comment by Niketkumardheeryan** [comment]
> > > > Styling for fonts in the file is not perfect. Please re-check.
> > > 
> > > 
> > > @Rutikab12 I have renamed and the styling seems fine now.Kindly review.
> > 
> > 
> > it will be better if you could add images or sample code with doc
> 
> @Niketkumardheeryan @Rutikab12 Okay I have added sample code but images I couldn't find so I have given plots to show in the code

one more suggestion - Don't underestimate documentation, work on your documentation wala part

**Pull request merged**
