### PR TITLE
Stair Cases Segmentation

### LINKED ISSUE #993: Stair Cases Segmentation
### Feature Description

I want to develop a  Stair Segmentation and Behavioral Cloning for Autonomous Stair Climbing

I got this idea by reading this [research paper](https://www.worldscientific.com/doi/abs/10.1142/S1793351X1940021X)

I want to implement this using PyTorch and Fast.ai library
@Niketkumardheeryan, @invigorzz313 sir could you please assign me this issue under GSSOC'24

### Use Case

Mobile robots are widely used in the surveillance industry, for military and industrial applications. In order to carry out surveillance tasks like urban search and rescue operation, the ability to traverse stairs is of immense significance. 

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by sreevidya-16**
I added this model
This issue fixes #993 issue

@Niketkumardheeryan, view this PR

### CODE REVIEW

**Comment by sreevidya-16** [comment]
@Niketkumardheeryan, @invigorzz313 , kindly view this PR

**Comment by Niketkumardheeryan** [comment]
@sreevidya-16 is this copied?

**Comment by sreevidya-16** [comment]
@Niketkumardheeryan, no sir

**Comment by Niketkumardheeryan** [comment]
> @Niketkumardheeryan, no sir

This repo belongs to Kanishka kataria ,who is she then

**Pull request closed without merging**
