### PR TITLE
Added object detection using coco dataset with yolo v5 advanced deep learning model

### PR DESCRIPTION
**Pull request by Panchadip-128**
This project implements an object detection system using YOLOv5, a cutting-edge real-time object detection model. The system is designed to identify and localize objects within images and video streams. Leveraging the COCO dataset for training, the project includes data preparation, model training, and evaluation.

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
@Panchadip-128 attach results in readme.md

**Comment by Panchadip-128** [comment]
Sir, output is there but still added in Readme as well from my side

**Comment by Panchadip-128** [comment]
@Niketkumardheeryan Sir I have added the result demo png in readme

**Comment by Panchadip-128** [comment]
Sir requesting you to pls review @Niketkumardheeryan

**Comment by Panchadip-128** [comment]
@Niketkumardheeryan Sir, i have tried to rectify the errors which might have been in
Please review once

**Pull request closed without merging**
