### PR TITLE
Password strength checker 

### PR DESCRIPTION
**Pull request by AkhilYadavPadala**
Added password strength checker model and deployed it as a web app.
I've added Readme file too..
kindly, review the changes and merge this PR with a gssoc tag and level.
@Niketkumardheeryan @invigorzz313 
closes issue #749

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
HI @AkhilYadavPadala ,good work , just use visualization libraries for better analysis , you have describe this(PLotly) in Readme.md file, And your readme.md file looks same as previous Project submitted by You , Try to add results in Readme.md file as well.

**Comment by AkhilYadavPadala** [comment]
make sense!
@Niketkumardheeryan

**Comment by AkhilYadavPadala** [comment]
> HI @AkhilYadavPadala ,good work , just use visualization libraries for better analysis , you have describe this(PLotly) in Readme.md file, And your readme.md file looks same as previous Project submitted by You , Try to add results in Readme.md file as well.

I've made changes that you had asked . kindly, review the changes : )
@Niketkumardheeryan

**Comment by Niketkumardheeryan** [comment]
@AkhilYadavPadala still no changes ,

**Comment by AkhilYadavPadala** [comment]
> @AkhilYadavPadala still no changes ,

I've visualized the data and added it in readme file too..
Are there any other changes required?
@Niketkumardheeryan

**Comment by Niketkumardheeryan** [comment]
@AkhilYadavPadala still no use of visualization library , make a new PR,

**Pull request closed without merging**
