### PR TITLE
Created Hindi letter classification Project

### LINKED ISSUE #536: Hindi Letter Classification
Predict Devanagari Hindi alphabets into 46 classes based on image using CNN.
will contain following classes: 
ka
kha
ga
gha
kna
cha
chha
ja
jha
yna
tamaatar
thaa
daa
dhaa
adna
tabala
tha
da
dha
na
pa
pha
ba
bha
ma
yaw
ra
la
waw
motosaw
petchiryakha
patalosaw
ha
chhya
tra
gya
0
1
2
3
4
5
6
7
8
9

Will create a web application for it

### PR DESCRIPTION
**Pull request by ishaanv1206**
## PR Description

This is a Hindi Alphabet classification web application created using Streamlit framework and utilizes LENET-50 CNN framework. I created the README.md files which contains introduction about project along with the snapshots of the web app and guidelines to run it locally. 

## Related Issues

- Closes #536 

### Checklist

- [x] I have gone through the Contributing Guidelines

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
hi @ishaanv1206  Great work, Please add .ipynb files rather than .py  , you can use  jupyter or google notebooks for that,

And Proper comment in your code as well, Because well documeneted code is more readable .

**Comment by ishaanv1206** [comment]
Okay sir i will add ipynb file and add more comments

**Comment by ishaanv1206** [comment]
Hi @Niketkumardheeryan  
Please check i added the ipynb file instead of python file and added more comments to the program.

**Comment by ishaanv1206** [comment]
@Niketkumardheeryan Please see to it sir

**Comment by ishaanv1206** [comment]
@Niketkumardheeryan please check my new PR

**Pull request merged**
