### PR TITLE
Parkinsons Disease detection

### PR DESCRIPTION
**Pull request by kaishwarya24**
created a Parkinson's disease detection model, and added Parkinson. ipynb file and parkinsons.csv file with a clear explanation in readme.md file and created a model with 100% accuracy with EDA, data balancing, feature selection, hyperparameter tuning
#582 is completed

### CODE REVIEW

**Comment by invigorzz313** [comment]
You have to create an issue before submitting a PR.
Also, this topic is repititive.

**Comment by kaishwarya24** [comment]
@invigorzz313 I have created issue #582 and it is assigned to me

**Comment by Niketkumardheeryan** [comment]
hey @kaishwarya24 , Please improve your readme .md file - add problem statement first , 100 % accuracy (I don't think it will be correct model please your accuracy model),

Make a PR for Branch name as - Capsule 1.1

**Comment by kaishwarya24** [comment]
definitely @Niketkumardheeryan, I will improve, and  thank you for your valuable insight, I will re-submit as soon as possible

**Comment by Niketkumardheeryan** [comment]
@kaishwarya24 ??

**Comment by kaishwarya24** [comment]
@Niketkumardheeryan Sorry, due to semester exams in our college I couldn't concentrate much on this give me a few days, and I will complete it.

**Comment by Niketkumardheeryan** [comment]
Create new updated PR ,

**Pull request closed without merging**
