### PR TITLE
Cheat sheets

### PR DESCRIPTION
**Pull request by Tanuj-rai**
I've created this pr in response to issue #445 
I've added the cheatsheets for Numpy, Pandas, Seaborn, and Matplotlib.

### CODE REVIEW

**Comment by Tanuj-rai** [comment]
@Rutikab12 can you please help me to remove this PR. I have committed to the same branch that's why new which was previously
created.

**Comment by Rutikab12** [comment]
> @Rutikab12 can you please help me to remove this PR. I have committed to the older branch which was previously created.

Cheat-sheets branch, right?

**Comment by Rutikab12** [comment]
> > @Rutikab12 can you please help me to remove this PR. I have committed to the older branch which was previously created.
> 
> Cheat-sheets branch, right?

Hey @Tanuj-rai I will close this PR. You can make fresh one. Don't worry. 
And don't just place links for resources, try to add some theories, plenty of cheat sheet images are available on social media , internet. Try to add that.

**Comment by Tanuj-rai** [comment]
> > > @Rutikab12 can you please help me to remove this PR. I have committed to the older branch which was previously created.
> > 
> > 
> > Cheat-sheets branch, right?
> 
> Hey @Tanuj-rai I will close this PR. You can make fresh one. Don't worry. And don't just place links for resources, try to add some theories, plenty of cheat sheet images are available on social media , internet. Try to add that.

Thank you I will add this too.

**Comment by Rutikab12** [comment]
> > > > @Rutikab12 can you please help me to remove this PR. I have committed to the older branch which was previously created.
> > > 
> > > 
> > > Cheat-sheets branch, right?
> > 
> > 
> > Hey @Tanuj-rai I will close this PR. You can make fresh one. Don't worry. And don't just place links for resources, try to add some theories, plenty of cheat sheet images are available on social media , internet. Try to add that.
> 
> Thank you I will add this too.

Yeah.

**Pull request closed without merging**
