### PR TITLE
Rock Paper Scissors Python Game

### PR DESCRIPTION
**Pull request by Mennatallah9**
Rock Paper Scissors Python Game issue#224.
Made a rock paper scissors python game. The game calculates the score of both the player and the computer and randomly selects option for computer using random module.
GSSoC'22 Contributor.

### CODE REVIEW

**Comment by Niketkumardheeryan** [comment]
@Mennatallah9 add .ipynb file(Jupyter notebooks or Google collab notebooks) and readme.md file as well ...

**Comment by Mennatallah9** [comment]
@Niketkumardheeryan Done!

**Comment by Niketkumardheeryan** [comment]
> @Niketkumardheeryan Done!

could you please add a demo in your reame.md file

**Comment by Mennatallah9** [comment]
> > @Niketkumardheeryan Done!
> 
> could you please add a demo in your reame.md file

Yes sure!

**Comment by Mennatallah9** [comment]
@Niketkumardheeryan  Sorry for the delay. I've updated the readme.md file could you check it out please?

**Pull request merged**
