### PR TITLE
Student Marks Prediction model added

### PR DESCRIPTION
**Pull request by AkhilYadavPadala**
#544 Issue solved
@Niketkumardheeryan @invigorzz313 
I've added documentation for deployment in readme file.
I've created a seperate branch for it.so,it doesn't conflict with master branch.
Kindly, review my PR and add level(1,2,3)
as a part of my GSSOC : )

### CODE REVIEW

**Comment by khushi-igupta** [comment]
Hello @invigorzz313 I am a GsSOC'24 contributor and I would like to work on this issue. Can you please assign it to me?

**Comment by AkhilYadavPadala** [comment]
@Niketkumardheeryan @invigorzz313 
I've made the changes that you asked for. Could you merge this PR?

**Comment by khushi-igupta** [comment]
Which one??

**Comment by Niketkumardheeryan** [comment]
@AkhilYadavPadala no changes here

**Comment by AkhilYadavPadala** [comment]
Should I make PR in capsule1.1 branch?
It has lots of commits in it , so I created seperate branch called SMP so it would easy to merge into main branch....
@Niketkumardheeryan

**Comment by AkhilYadavPadala** [comment]
I've push the changes to Capsule1.1 as requested
kindly, look into this @Niketkumardheeryan

**Pull request merged**
